/*
 * Copyright(c) 1997-2001 id Software, Inc.
 * Copyright(c) 2002 The Quakeforge Project.
 * Copyright(c) 2006 Quetoo.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

#pragma once

#include "shared/shared.h"
#include "collision/cm_types.h"

/**
 * @brief Game protocol version (protocol minor version). To be incremented
 * whenever the game protocol changes.
 */
#define PROTOCOL_MINOR 1021

/**
 * @brief Game-specific server protocol commands. These are parsed directly by
 * the client game module.
 */
typedef enum {
  SV_CMD_SOUND = SV_CMD_CGAME, ///< Plays a positional sound effect.
  SV_CMD_MUZZLE_FLASH,         ///< Shows a muzzle flash bound to an entity.
  SV_CMD_TEMP_ENTITY,          ///< Spawns a temporary positional effect.
  SV_CMD_VIEW_KICK,            ///< Applies a view kick angle to the client.
  SV_CMD_CENTER_PRINT,         ///< Displays a centered text message to the client.
  SV_CMD_SCORES,               ///< Transmits the current scoreboard data.
} g_sv_packet_cmd_t;

/**
 * @brief Game-specific client protocol commands. These are parsed directly by
 * the game module.
 */
typedef enum {
  CL_CMD_EXAMPLE = CL_CMD_CGAME, ///< Placeholder example client game command.
} g_cl_packet_cmd_t;

/**
 * @brief The name of the map list generated by the user interface.
 */
#define MAP_LIST_UI "maps.ui.lst"

/**
 * @brief Map list entries describe available gameplay parameters for a given map.
 */
typedef struct {
  char name[32];                ///< Map file name.
  char message[128];            ///< Descriptive map title shown in the UI.
  int32_t gravity;              ///< Override gravity, or 0 for default.
  int32_t gameplay;             ///< Override gameplay mode, or -1 for default.
  int32_t hook;                 ///< Override hook setting, or -1 for default.
  int32_t teams;                ///< Override teams setting, or -1 for default.
  int32_t num_teams;            ///< Number of teams, or 0 for default.
  int32_t techs;                ///< Override techs setting, or -1 for default.
  int32_t ctf;                  ///< Override CTF setting, or -1 for default.
  int32_t frag_limit;           ///< Override frag limit, or 0 for default.
  int32_t capture_limit;        ///< Override capture limit, or 0 for default.
  float time_limit;             ///< Override time limit in minutes, or 0 for default.
  char give[MAX_STRING_CHARS];  ///< Items to give to all players on spawn.
  char music[MAX_STRING_CHARS]; ///< Background music track.
} g_map_list_map_t;

/**
 * @brief ConfigStrings that are local to the game module.
 */
#define CS_GAMEPLAY        (CS_GAME + 0)  // gameplay string
#define CS_CTF             (CS_GAME + 1)  // is capture enabled?
#define CS_TEAM_INFO       (CS_GAME + 2)  // team info, separated by \ (name\color\name\color, etc)
#define CS_TIME            (CS_GAME + 3)  // map time
#define CS_HOOK_PULL_SPEED (CS_GAME + 4)  // hook speed
#define CS_MAX_CLIENTS     (CS_GAME + 5)  // max clients of server
#define CS_NUM_CLIENTS     (CS_GAME + 6)  // number of players in server
#define CS_NUM_TEAMS       (CS_GAME + 7)  // number of teams (0 - MAX_TEAMS)
#define CS_WEAPONS         (CS_GAME + 8)  // weapon list, for the change weapon UI
#define CS_NAV_EDIT        (CS_GAME + 9) // nav edit mode

/**
 * @brief Player state statistics (inventory, score, etc).
 */
typedef enum {
  STAT_AMMO,           ///< Current ammo count.
  STAT_AMMO_ICON,      ///< Ammo icon image index.
  STAT_AMMO_LOW,       ///< Set when ammo is critically low.
  STAT_ARMOR,          ///< Current armor value.
  STAT_ARMOR_ICON,     ///< Armor icon image index.
  STAT_CAPTURES,       ///< Number of flag captures.
  STAT_CHASE,          ///< Index of the player being spectated.
  STAT_DAMAGE_ARMOR,   ///< Damage absorbed by armor this frame.
  STAT_DAMAGE_HEALTH,  ///< Damage taken to health this frame.
  STAT_DAMAGE_INFLICT, ///< Damage dealt to other players this frame.
  STAT_FRAGS,          ///< Frag count.
  STAT_DEATHS,         ///< Death count.
  STAT_HEALTH,         ///< Current health value.
  STAT_HEALTH_ICON,    ///< Health icon image index.
  STAT_CARRYING_FLAG,  ///< Non-zero if the player is carrying a flag.
  STAT_PICKUP_ICON,    ///< Recently picked-up item icon index.
  STAT_PICKUP_STRING,  ///< Recently picked-up item name string index.
  STAT_QUAD_TIME,      ///< Remaining quad damage duration.
  STAT_SCORES,         ///< Layout flags for scoreboard display.
  STAT_SPECTATOR,      ///< Non-zero if the player is a spectator.
  STAT_TEAM,           ///< Current team index.
  STAT_TIME,           ///< Level time string index.
  STAT_WEAPON,         ///< Active weapon item index.
  STAT_WEAPON_ICON,    ///< Active weapon icon image index.
  STAT_WEAPON_TAG,     ///< Low 8 bits = current weapon tag, high 8 bits = switching weapon tag.
  STAT_WEAPONS,        ///< Bitmask of available weapons for the switcher.
  STAT_TECH_ICON       ///< Currently held tech powerup icon index.
} g_stat_t;

/**
 * @brief Forces a statistic field to be re-sent, even if the value has not changed.
 */
#define STAT_TOGGLE_BIT 0x4000

/**
 * @brief Muzzle flashes are bound to the entity that created them. This allows
 * the protocol to forego sending the origin and angles for the effect, as they
 * can be inferred from the referenced entity.
 */
typedef enum {
  MZ_BLASTER,          ///< Blaster muzzle flash.
  MZ_SHOTGUN,          ///< Shotgun muzzle flash.
  MZ_SUPER_SHOTGUN,    ///< Super shotgun muzzle flash.
  MZ_MACHINEGUN,       ///< Machinegun muzzle flash.
  MZ_GRENADE_LAUNCHER, ///< Grenade launcher muzzle flash.
  MZ_ROCKET_LAUNCHER,  ///< Rocket launcher muzzle flash.
  MZ_HYPERBLASTER,     ///< Hyperblaster muzzle flash.
  MZ_LIGHTNING,        ///< Lightning gun muzzle flash.
  MZ_RAILGUN,          ///< Railgun muzzle flash.
  MZ_BFG10K,           ///< BFG10K muzzle flash.
  MZ_LOGOUT,           ///< Logout (disconnect) flash effect.
} g_muzzle_flash_t;

/**
 * @brief Temporary entities are positional events that are not explicitly
 * bound to a game entity (g_entity_t). Examples are explosions, certain weapon
 * trails and other short-lived effects.
 */
typedef enum {
  TE_TELEPORT,            ///< Teleport arrival effect.
  TE_BLASTER,             ///< Blaster impact spark.
  TE_TRACER,              ///< Projectile tracer streak.
  TE_BULLET,              ///< Bullet impact.
  TE_BLOOD,               ///< Blood splatter on hit.
  TE_SPARKS,              ///< Electric spark shower.
  TE_HYPERBLASTER,        ///< Hyperblaster impact effect.
  TE_LIGHTNING_DISCHARGE, ///< Lightning discharge at contact point.
  TE_RAIL,                ///< Railgun beam and impact.
  TE_EXPLOSION,           ///< Generic explosion.
  TE_BUBBLES,             ///< Underwater bubbles trail.
  TE_BFG_LASER,           ///< BFG10K targeting laser.
  TE_BFG,                 ///< BFG10K impact explosion.
  TE_GIB,                 ///< Gibs burst from a death.
  TE_RIPPLE,              ///< Liquid surface ripple.
  TE_HOOK_IMPACT,         ///< Hook projectile impact.
  TE_AI_NODE,             ///< AI navigation node visualization.
  TE_AI_NODE_LINK         ///< AI navigation node link visualization.
} g_temp_entity_t;

/**
 * @brief Sound playback flags.
 */
#define SOUND_ENTITY    (1 << 0)
#define SOUND_ORIGIN    (1 << 1)
#define SOUND_ATTEN     (1 << 2)
#define SOUND_PITCH     (1 << 3)

/**
 * @brief Sound playback dispatch. Sounds may be associated with an entity, or simply positioned.
 */
typedef struct {
  int32_t index;                   ///< ConfigString index of the sample to play.
  const struct g_entity_s *entity; ///< Entity to bind the sound to for positioning.
  const vec3_t *origin;            ///< Sound origin, takes precedence over the entity origin.
  sound_atten_t atten;             ///< Attenuation model.
  int8_t pitch;                    ///< Pitch shift in tones; 8 tones per octave.
} g_play_sound_t;

/**
 * @brief Player scores are transmitted as binary to the client game module.
 */
typedef struct {
  uint16_t client;  ///< Client number.
  int16_t ping;     ///< Round-trip latency in milliseconds.
  int16_t color;    ///< Team or player color hue.
  int16_t score;    ///< Frag or point score.
  int16_t captures; ///< Number of flag captures.
  uint16_t deaths;  ///< Number of deaths.
  uint8_t flags;    ///< Score flags (SCORE_CTF_FLAG, etc.).
  uint8_t team;     ///< Team index.
} g_score_t;

/**
 * @brief Player scores flags.
 */
#define SCORE_CTF_FLAG  (1 << 0)
#define SCORE_SPECTATOR (1 << 2)
#define SCORE_AGGREGATE (1 << 3)

/**
 * @brief Game-specific entity events.
 */
typedef enum {
  EV_CLIENT_TELEPORT = EV_GAME, ///< Client teleported.
  EV_CLIENT_DROWN,              ///< Client is drowning.
  EV_CLIENT_FALL,               ///< Client landed after a short fall.
  EV_CLIENT_FALL_FAR,           ///< Client landed after a long fall.
  EV_CLIENT_FOOTSTEP,           ///< Client footstep sound.
  EV_CLIENT_GURP,               ///< Client gurgling (water entry).
  EV_CLIENT_JUMP,               ///< Client jumped.
  EV_CLIENT_LAND,               ///< Client landed.
  EV_CLIENT_SIZZLE,             ///< Client is sizzling in slime or lava.
  EV_ITEM_RESPAWN,              ///< An item has respawned.
  EV_ITEM_PICKUP,               ///< An item was picked up.
} g_entity_event_t;

/**
 * @brief Game-specific entity state effects.
 */
#define EF_ROTATE     (EF_GAME << 0) // rotate on z
#define EF_BOB        (EF_GAME << 1) // bob on z
#define EF_INACTIVE   (EF_GAME << 2) // inactive icon for when input is not going to game
#define EF_BEAM       (EF_GAME << 3) // overloads old_origin for endpoint
#define EF_CORPSE     (EF_GAME << 4) // to differentiate own corpse from self
#define EF_RESPAWN    (EF_GAME << 5) // yellow shell
#define EF_QUAD       (EF_GAME << 6) // blue-green shell
#define EF_CTF_RED    (EF_GAME << 7) // carrying the red flag
#define EF_CTF_BLUE   (EF_GAME << 8) // carrying the blue flag
#define EF_CTF_YELLOW (EF_GAME << 9) // carrying the yellow flag
#define EF_CTF_GREEN  (EF_GAME << 10) // carrying the green flag
#define EF_DESPAWN    (EF_GAME << 11) // translucent
#define EF_LIGHT      (EF_GAME << 12) // colored light
#define EF_TEAM_TINT  (EF_GAME << 13) // tint by the team color provided

#define EF_CTF_MASK   (EF_CTF_RED | EF_CTF_BLUE | EF_CTF_YELLOW | EF_CTF_GREEN)

/**
 * @brief The lightning gun overrides animation1 to inform the client what
 * kind of trail to render.
 */
#define LIGHTNING_NO_HIT    0
#define LIGHTNING_SOLID_HIT 1

/**
 * @brief Game-specific entity state trails.
 */
typedef enum {
  TRAIL_BLASTER = TRAIL_GAME, ///< Blaster bolt trail.
  TRAIL_GRENADE,              ///< Grenade smoke trail.
  TRAIL_ROCKET,               ///< Rocket exhaust trail.
  TRAIL_HYPERBLASTER,         ///< Hyperblaster bolt trail.
  TRAIL_LIGHTNING,            ///< Lightning beam trail.
  TRAIL_BFG,                  ///< BFG energy ball trail.
  TRAIL_TELEPORTER,           ///< Teleporter swirl trail.
  TRAIL_GIB,                  ///< Gib blood trail.
  TRAIL_FIREBALL,             ///< Fireball flame trail.
  TRAIL_HOOK,                 ///< Grappling hook cable trail.
  TRAIL_PLAYER_SPAWN          ///< Player spawn marker trail.
} g_entity_trail_t;

/**
 * @brief Scoreboard background color hues.
 */
#define TEAM_COLOR_RED    color_hue_red
#define TEAM_COLOR_BLUE   color_hue_blue
#define TEAM_COLOR_YELLOW color_hue_yellow
#define TEAM_COLOR_GREEN  color_hue_green

/**
 * @brief Team ID
 */
typedef enum {
  TEAM_NONE = -1, ///< No team assignment.
  TEAM_RED,       ///< Red team.
  TEAM_BLUE,      ///< Blue team.
  TEAM_YELLOW,    ///< Yellow team.
  TEAM_GREEN,     ///< Green team.

  MAX_TEAMS       ///< Number of teams.
} g_team_id_t;

/**
 * @brief Entity state model number to indicate that the entity is a client.
 * When this is set, the model should be resolved from `CS_CLIENTS`.
 */
#define MODEL_CLIENT 0xff

/**
 * @brief Weapon handedness.
 */
typedef enum {
  HAND_CENTER, ///< Weapon drawn in the center.
  HAND_RIGHT,  ///< Weapon drawn on the right.
  HAND_LEFT    ///< Weapon drawn on the left.
} g_hand_t;

/**
 * @brief Game modes. These are selected via `g_gameplay` and sent to client via ConfigString.
 */
typedef enum {
  GAME_DEATHMATCH, ///< Standard deathmatch.
  GAME_INSTAGIB,   ///< Instagib mode (one-hit kills).
  GAME_ARENA       ///< Arena mode (round-based).
} g_gameplay_t;

/**
 * @brief Hook style.
 */
typedef enum {
  HOOK_PULL,         ///< Lithium-style pull hook.
  HOOK_SWING_MANUAL, ///< Hookmod-style manually controlled swing hook.
  HOOK_SWING_AUTO    ///< Xotonic-style automatically swinging hook.
} g_hook_style_t;

/**
 * @brief Item types.
 */
typedef enum {
  ITEM_AMMO,    ///< Ammunition item.
  ITEM_ARMOR,   ///< Armor item.
  ITEM_FLAG,    ///< Capture the flag flag entity.
  ITEM_HEALTH,  ///< Health pack.
  ITEM_POWERUP, ///< Powerup item.
  ITEM_WEAPON,  ///< Weapon item.
  ITEM_TECH,    ///< Tech powerup item.

  ITEM_TOTAL    ///< Total number of item types.
} g_item_type_t;

/**
 * @brief Weapon tags to inform the client game which weapon the player wields and
 * the order of the weapon switcher.
 */
typedef enum {
  WEAPON_NONE,             ///< No weapon.

  WEAPON_BLASTER,          ///< Blaster.
  WEAPON_SHOTGUN,          ///< Shotgun.
  WEAPON_SUPER_SHOTGUN,    ///< Super shotgun.
  WEAPON_MACHINEGUN,       ///< Machinegun.
  WEAPON_HAND_GRENADE,     ///< Hand grenade.
  WEAPON_GRENADE_LAUNCHER, ///< Grenade launcher.
  WEAPON_ROCKET_LAUNCHER,  ///< Rocket launcher.
  WEAPON_HYPERBLASTER,     ///< Hyperblaster.
  WEAPON_LIGHTNING,        ///< Lightning gun.
  WEAPON_RAILGUN,          ///< Railgun.
  WEAPON_BFG10K,           ///< BFG10K.

  WEAPON_TOTAL             ///< Total number of weapon tags.
} g_weapon_tag_t;

/**
 * @brief Weapon flags provide hints to indicate weapon use.
 */
typedef enum {
  WF_PROJECTILE  = (1 << 0), ///< Fires a projectile with the weapon's speed.
  WF_HITSCAN     = (1 << 1), ///< Fires hitscan shot(s).
  WF_TIMED       = (1 << 2), ///< Holdable that must be thrown within the weapon's time limit.
  WF_EXPLOSIVE   = (1 << 3), ///< Fires explosive shots that may damage the shooter.
  WF_SHORT_RANGE = (1 << 4), ///< Effective at close range.
  WF_MED_RANGE   = (1 << 5), ///< Effective at medium range.
  WF_LONG_RANGE  = (1 << 6)  ///< Effective at long range.
} g_weapon_flags_t;

/**
 * @brief Ammunition types.
 */
typedef enum {
  AMMO_SHELLS,   ///< Shotgun shells.
  AMMO_BULLETS,  ///< Machinegun bullets.
  AMMO_GRENADES, ///< Grenades.
  AMMO_ROCKETS,  ///< Rockets.
  AMMO_CELLS,    ///< Energy cells.
  AMMO_BOLTS,    ///< Lightning bolts.
  AMMO_SLUGS,    ///< Railgun slugs.
  AMMO_NUKES,    ///< BFG nukes.

  AMMO_TOTAL     ///< Total number of ammo types.
} g_ammo_t;

/**
 * @brief Armor types.
 */
typedef enum {
  ARMOR_SHARD,  ///< Small armor shard.
  ARMOR_JACKET, ///< Jacket armor (25 points).
  ARMOR_COMBAT, ///< Combat armor (50 points).
  ARMOR_BODY,   ///< Body armor (100 points).

  ARMOR_TOTAL   ///< Total number of armor types.
} g_armor_t;

/**
 * @brief Armor attributes.
 */
typedef struct {
  g_armor_t tag;           ///< Armor type tag.
  float normal_protection; ///< Protection fraction against normal damage.
  float energy_protection; ///< Protection fraction against energy damage.
} g_armor_info_t;

/**
 * @brief Health types.
 */
typedef enum {
  HEALTH_SMALL,  ///< Small health pack.
  HEALTH_MEDIUM, ///< Medium health pack.
  HEALTH_LARGE,  ///< Large health pack.
  HEALTH_MEGA,   ///< Mega health (temporarily boosts above max).

  HEALTH_TOTAL   ///< Total number of health types.
} g_health_t;

/**
 * @brief Powerup types.
 */
typedef enum {
  POWERUP_QUAD,       ///< Quad damage powerup.
  POWERUP_ADRENALINE, ///< Adrenaline powerup (restores to full health).

  POWERUP_TOTAL       ///< Total number of powerup types.
} g_powerup_t;

/**
 * @brief Tech types.
 */
typedef enum {
  TECH_HASTE,    ///< Haste tech (increased fire rate).
  TECH_REGEN,    ///< Regeneration tech (passive health regen).
  TECH_RESIST,   ///< Resistance tech (reduced incoming damage).
  TECH_STRENGTH, ///< Strength tech (increased outgoing damage).
  TECH_VAMPIRE,  ///< Vampire tech (health stolen on hit).

  TECH_TOTAL     ///< Total number of tech types.
} g_tech_t;

#if defined(__GAME_LOCAL_H__)

/**
 * @brief This file will define the game-visible definitions of g_client_t
 * and g_entity_t. They are much larger than the server-visible definitions,
 * which are intentionally truncated stubs.
 */
typedef struct g_client_s g_client_t;
typedef struct g_entity_s g_entity_t;

/**
 * @brief Spawn flags for g_entity_t are set in the level editor.
 */
#define SF_ITEM_TRIGGER  0x00000001
#define SF_ITEM_NO_TOUCH 0x00000002
#define SF_ITEM_HOVER    0x00000004

/**
 * @brief These spawn flags are actually set by the game module on entities
 * that are programmatically instantiated.
 */
#define SF_ITEM_DROPPED      0x00010000
#define SF_ITEM_TARGETS_USED 0x00020000

/**
 * @brief Entity flags (g_entity_locals.flags). These again are mostly for
 * backwards compatibility with Quake II.
 */
#define FL_FLY        0x00000001
#define FL_SWIM       0x00000002  // implied immunity to drowning
#define FL_GOD_MODE   0x00000004
#define FL_TEAM_SLAVE 0x00000008  // not the first on the team

/**
 * @brief Move types govern the physics dispatch in G_RunEntity.
 */
typedef enum {
  MOVE_TYPE_NONE,    ///< Never moves.
  MOVE_TYPE_NO_CLIP, ///< Never interacts with the world.
  MOVE_TYPE_PUSH,    ///< No clip to world; pushes entities on box contact.
  MOVE_TYPE_STOP,    ///< No clip to world; stops on box contact.

  MOVE_TYPE_WALK,    ///< Uses Pm_Move for client movement.
  MOVE_TYPE_FLY,     ///< Clips to world and boxes; no gravity.
  MOVE_TYPE_BOUNCE   ///< Clips to world and boxes; gravity; bounces on impact.
} g_move_type_t;

/**
 * @brief A synonym for readability; MOVE_TYPE_THINK implies that the entity's
 * Think function will update its origin and handle other interactions.
 */
#define MOVE_TYPE_THINK MOVE_TYPE_NONE

/**
 * @brief Items are touchable entities that players visit to acquire inventory.
 */
typedef struct g_item_s {
  const char *classname;                                            ///< Entity classname used for map spawning.
  bool (*Pickup)(g_client_t *cl, g_entity_t *it);                   ///< Called when a player touches the item; return false to prevent pickup.
  void (*Use)(g_client_t *cl, const struct g_item_s *item);         ///< Called when the item is activated from inventory.
  g_entity_t *(*Drop)(g_client_t *cl, const struct g_item_s *item); ///< Called to drop the item; returns the dropped entity or NULL.
  void (*Think)(g_client_t *cl);                                    ///< Called every frame for a player holding this weapon.
  const char *ammo;                                                 ///< Name of the ammo item this weapon consumes.
  const char *pickup_sound;                                         ///< Sound to play on pickup.
  const char *model;                                                ///< World model path.
  uint32_t effects;                                                 ///< Entity effect flags on the pickup entity.
  const char *icon;                                                 ///< Icon image path, used on HUD and in pickup messages.
  const char *name;                                                 ///< Display name.
  uint16_t quantity;                                                ///< Amount provided or consumed, depending on type.
  uint16_t max;                                                     ///< Maximum amount the player can carry (ammo/armor).
  uint16_t tag;                                                     ///< Type-specific tag (e.g. g_weapon_tag_t, g_ammo_t).
  uint16_t flags;                                                   ///< Type-specific flags (e.g. g_weapon_flags_t).
  g_item_type_t type;                                               ///< Item type category.
  float priority;                                                   ///< Relative priority used by AI for item selection.
  const char *precaches;                                            ///< Space-separated list of assets to precache.
  uint16_t index;                                                   ///< Index in the global item list; calculated at init.
  const struct g_item_s *ammo_item;                                 ///< Pointer to the ammo item; calculated at init.
  uint16_t icon_index;                                              ///< Precached icon image index; calculated at init.
  uint16_t model_index;                                             ///< Precached model index; calculated at init.
  uint16_t pickup_sound_index;                                      ///< Precached pickup sound index; calculated at init.
} g_item_t;

#define EOFS(x) (ptrdiff_t) &(((g_entity_t *) 0)->x)

/**
 * @brief Movement states.
 */
typedef enum {
  MOVE_STATE_BOTTOM,     ///< Entity is at its bottom/start position.
  MOVE_STATE_GOING_UP,   ///< Entity is moving toward the top position.
  MOVE_STATE_GOING_DOWN, ///< Entity is moving toward the bottom position.
  MOVE_STATE_TOP,        ///< Entity is at its top/end position.
} g_move_state_t;

/**
 * @brief Physics parameters and think functions for entities which move.
 */
typedef struct {
  vec3_t start_origin;        ///< Starting origin.
  vec3_t start_angles;        ///< Starting angles.
  vec3_t end_origin;          ///< Ending origin.
  vec3_t end_angles;          ///< Ending angles.

  uint16_t sound_start;       ///< Sound played when movement begins.
  uint16_t sound_middle;      ///< Sound played while moving.
  uint16_t sound_end;         ///< Sound played when movement ends.

  float accel;                ///< Acceleration rate.
  float speed;                ///< Constant travel speed.
  float decel;                ///< Deceleration rate.
  float distance;             ///< Total distance to travel.

  float wait;                 ///< Time to wait at each end before reversing.

  g_move_state_t state;       ///< Current movement state.
  vec3_t dest;                ///< Current target destination.
  vec3_t dir;                 ///< Direction of travel.
  float current_speed;        ///< Current movement speed.
  int32_t const_frames;       ///< Number of frames the move uses constant speed.
  int32_t accel_frames;       ///< Number of frames the move is accelerating.
  int32_t decel_frames;       ///< Number of frames the move is decelerating.
  void (*Done)(g_entity_t *); ///< Callback invoked when the move completes.
} g_move_info_t;

#define NUM_GIB_MODELS 4
#define NUM_GIB_SOUNDS 3

/**
 * @brief This structure holds references to frequently accessed media.
 */
typedef struct {
  struct g_media_items_t {
    const g_item_t *ammo[AMMO_TOTAL];
    const g_item_t *armor[ARMOR_TOTAL];
    const g_item_t *flags[MAX_TEAMS];
    const g_item_t *health[HEALTH_TOTAL];
    const g_item_t *powerups[POWERUP_TOTAL];
    const g_item_t *weapons[WEAPON_TOTAL];
    const g_item_t *techs[TECH_TOTAL];
  } items;

  struct g_media_models_t {
    uint16_t gibs[NUM_GIB_MODELS];

    uint16_t grenade;
    uint16_t rocket;
    uint16_t hook;

    uint16_t fireball;
  } models;

  struct g_media_sounds_t {
    uint16_t gib_hits[NUM_GIB_SOUNDS];

    uint16_t bfg_hit;
    uint16_t bfg_prime;
    uint16_t grenade_hit;
    uint16_t grenade_throw;
    uint16_t rocket_fly;
    uint16_t lightning_fly;
    uint16_t quad_attack;
    uint16_t quad_expire;

    uint16_t hook_fire;
    uint16_t hook_hit;
    uint16_t hook_pull;
    uint16_t hook_fly;
    uint16_t hook_detach;
    uint16_t hook_gibhit;

    uint16_t teleport;

    uint16_t water_in;
    uint16_t water_out;

    uint16_t weapon_no_ammo;
    uint16_t weapon_switch;

    uint16_t countdown[11];

    uint16_t roar;

    uint16_t techs[TECH_TOTAL];

    uint16_t chat;
  } sounds;

  struct g_media_images_t {
    uint16_t health;
  } images;
} g_media_t;

/**
 * @brief A list of spawn point entities available for player spawning.
 */
typedef struct {
  uint32_t count;     ///< Number of spawn point entities.
  g_entity_t **spots; ///< Array of spawn point entity pointers.
} g_spawn_points_t;

/**
 * @brief The main structure for all world management. This is cleared at each
 * level load.
 */
typedef struct {
  uint32_t frame_num;            ///< Current server frame number.
  uint32_t time;                 ///< Level time in milliseconds.

  char title[MAX_STRING_CHARS];  ///< Descriptive map name (e.g. "Stress Fractures").
  char name[MAX_QPATH];          ///< Short server map name (e.g. "fractures").
  int16_t gravity;               ///< Gravity override.
  g_gameplay_t gameplay;         ///< Active gameplay mode.
  bool teams;                    ///< True if team play is active.
  bool ctf;                      ///< True if capture the flag is active.
  bool techs;                    ///< True if tech powerups are enabled.
  bool hook;                     ///< True if the grappling hook is enabled.
  int32_t num_teams;             ///< Number of active teams.
  int32_t hook_map;              ///< Map-specified hook allowance, used for voting and restarts.
  int32_t techs_map;             ///< Map-specified techs allowance.
  int32_t frag_limit;            ///< Frag limit; game ends when a player reaches this.
  int32_t capture_limit;         ///< Capture limit; game ends when a team reaches this.
  int32_t time_limit;            ///< Time limit in minutes; game ends when exceeded.
  char give[MAX_STRING_CHARS];   ///< Items to give all players on spawn.
  char music[MAX_STRING_CHARS];  ///< Background music track.

  uint32_t scores_time;          ///< Level time when scores were last updated.

  uint32_t intermission_time;    ///< Level time when intermission began.
  vec3_t intermission_origin;    ///< Camera origin during intermission.
  vec3_t intermission_angle;     ///< Camera angles during intermission.
  const char *next_map;          ///< Next map name to load after intermission.

  g_entity_t *current_entity;    ///< Entity currently being processed by G_RunFrame.

  g_spawn_points_t spawn_points; ///< Global spawn points (used in non-team modes).
} g_level_t;

/**
 * @brief Means of death.
 */
 typedef enum {
  MOD_UNKNOWN,                  ///< Unknown cause of death.
  MOD_BLASTER,                  ///< Killed by blaster.
  MOD_SHOTGUN,                  ///< Killed by shotgun.
  MOD_SUPER_SHOTGUN,            ///< Killed by super shotgun.
  MOD_MACHINEGUN,               ///< Killed by machinegun.
  MOD_GRENADE,                  ///< Killed by direct grenade hit.
  MOD_GRENADE_SPLASH,           ///< Killed by grenade splash damage.
  MOD_ROCKET,                   ///< Killed by direct rocket hit.
  MOD_ROCKET_SPLASH,            ///< Killed by rocket splash damage.
  MOD_HYPERBLASTER,             ///< Killed by hyperblaster.
  MOD_HYPERBLASTER_CLIMB,       ///< Killed by hyperblaster while climbing.
  MOD_LIGHTNING,                ///< Killed by lightning gun.
  MOD_LIGHTNING_DISCHARGE,      ///< Killed by lightning discharge in water.
  MOD_RAILGUN,                  ///< Killed by railgun.
  MOD_BFG_LASER,                ///< Killed by BFG laser beam.
  MOD_BFG_BLAST,                ///< Killed by BFG explosion.
  MOD_WATER,                    ///< Drowned.
  MOD_SLIME,                    ///< Died in slime.
  MOD_LAVA,                     ///< Died in lava.
  MOD_CRUSH,                    ///< Crushed by a mover.
  MOD_TELEFRAG,                 ///< Telefragged.
  MOD_FALLING,                  ///< Died from fall damage.
  MOD_SUICIDE,                  ///< Committed suicide.
  MOD_EXPLOSIVE,                ///< Killed by a generic explosive.
  MOD_TRIGGER_HURT,             ///< Killed by a hurt trigger.
  MOD_HANDGRENADE,              ///< Killed by direct hand grenade hit.
  MOD_HANDGRENADE_SPLASH,       ///< Killed by hand grenade splash.
  MOD_HANDGRENADE_SUICIDE,      ///< Killed own self with hand grenade.
  MOD_HANDGRENADE_KAMIKAZE,     ///< Killed by grenade on death.
  MOD_FIREBALL,                 ///< Killed by fireball.
  MOD_HOOK,                     ///< Killed by grappling hook.
  MOD_ACT_OF_GOD,               ///< Killed by an act of god (trigger_hurt or similar).
  MOD_FRIENDLY_FIRE = 0x8000000 ///< Flag combined with another MOD to indicate friendly fire.
} g_means_of_death;

/**
 * @brief Damage flags. These can be and often are combined.
 */
#define DMG_RADIUS   0x1  // damage was indirect
#define DMG_ENERGY   0x2  // damage is from an energy based weapon
#define DMG_BULLET   0x4  // damage is from a bullet
#define DMG_NO_ARMOR 0x8  // armor does not protect from this damage
#define DMG_NO_GOD   0x10  // armor and god mode have no effect

/**
 * @brief Damage parameters for G_Damage.
 */
typedef struct {
	g_entity_t *target;    ///< Entity receiving the damage.
	g_entity_t *inflictor; ///< Entity that dealt the damage (projectile, explosion, etc.).
	g_entity_t *attacker;  ///< Entity responsible for the damage (player, etc.).
	vec3_t dir;            ///< Direction the damage came from.
	vec3_t point;          ///< World point where the damage was applied.
	vec3_t normal;         ///< Surface normal at the damage point.
	int32_t damage;        ///< Amount of damage to apply.
	int32_t knockback;     ///< Knockback force to apply.
	int32_t flags;         ///< Damage flags (DMG_RADIUS, DMG_ENERGY, etc.).
	g_means_of_death mod;  ///< Means of death identifier.
} g_damage_t;

/**
 * @brief The name for the CTF skin used in team games.
 */
#define DEFAULT_TEAM_SKIN "ctf"

/**
 * @brief There are four teams in the default game module.
 */
typedef struct {
  g_team_id_t id;                ///< Team identifier, used for comparison instead of pointer equality.

  char name[16];                 ///< Short team name for HUD display.
  char skin[32];                 ///< Team skin name.
  char flag[32];                 ///< Flag entity classname.
  char spawn[32];                ///< Spawn point classname.

  color_t shirt, pants, helmet;  ///< Team player colors.

  int16_t color;                 ///< Team color hue.
  int16_t effect;                ///< Entity effect for the team flag.

  int16_t score;                 ///< Team score.
  int16_t captures;              ///< Team capture count.

  g_spawn_points_t spawn_points; ///< Spawn points for this team.
  g_entity_t *flag_entity;       ///< The team's flag entity.
} g_team_t;

/**
 * @brief The default player model
 */
#define DEFAULT_USER_MODEL "qforcer"

/**
 * @brief The default player skin
 */
#define DEFAULT_USER_SKIN "default"

/**
 * @brief The default user info string (name and skin).
 */
#define DEFAULT_USER_INFO "\\name\\newbie\\skin\\" DEFAULT_USER_MODEL "/" DEFAULT_USER_SKIN

/**
 * @brief The full length of a net name, in bytes (including non-printables).
 */
#define MAX_NET_NAME 64

/**
 * @brief The maximum printable length of a net name.
 */
#define MAX_NET_NAME_PRINTABLE 15

/**
 * @brief This structure contains client data that persists over multiple spawns.
 */
typedef struct {
  uint32_t first_frame;                   ///< Frame number when the client first entered the game.

  char user_info[MAX_INFO_STRING_STRING]; ///< Raw user info key-value string.
  char net_name[MAX_NET_NAME];            ///< Display name.
  char skin[MAX_QPATH];                   ///< Player model/skin path.
  g_hand_t hand;                          ///< Weapon handedness preference.

  uint16_t auto_switch;                   ///< Non-zero if weapons should auto-switch on pickup.

  g_hook_style_t hook_style;              ///< The player's selected hook style.

  g_team_t *team;                         ///< Current team assignment.

  int16_t color;                          ///< Player effect color hue.
  color_t shirt, pants, helmet;           ///< Player clothing colors.

  int16_t score;                          ///< Current score.
  int16_t captures;                       ///< Number of flag captures.
  uint16_t deaths;                        ///< Number of deaths.

  bool admin;                             ///< True if the player has admin privileges.
  bool spectator;                         ///< True if the player is a spectator.
  bool muted;                             ///< True if the player is muted.
} g_client_persistent_t;

/**
 * @brief This structure is cleared on each spawn, with the persistent structure
 * explicitly copied over to preserve team membership, etc. This structure
 * extends the server-visible definition to provide all of the state management
 * the game module requires.
 */
struct g_client_s {
  g_entity_t *entity;               ///< The entity bound to this client.
  player_state_t ps;                ///< Player state communicated to clients by the server.
  uint32_t ping;                    ///< Current round-trip latency in milliseconds.
  bool in_use;                      ///< True if this client slot is currently active.
  struct ai_s *ai;                  ///< Non-null if this client is a bot.
  g_client_persistent_t persistent; ///< Data that persists across respawns.
  pm_cmd_t cmd;                     ///< Most recently received movement command.

  int16_t inventory[MAX_ITEMS];     ///< Item inventory counts indexed by item index.

  const g_item_t *weapon;           ///< Currently active weapon.
  const g_item_t *prev_weapon;      ///< Previously active weapon.
  const g_item_t *next_weapon;      ///< Weapon currently being switched to.

  uint16_t ammo_index;              ///< Inventory index of the current weapon's ammo.

  uint32_t buttons;                 ///< Current frame button state.
  uint32_t old_buttons;             ///< Previous frame button state.
  uint32_t latched_buttons;         ///< Buttons pressed this frame (edge-triggered).

  uint32_t weapon_think_time;       ///< Level time when the weapon think was last called.
  uint32_t weapon_fire_time;        ///< Weapon may fire again when time exceeds this.
  uint32_t weapon_fired_time;       ///< Level time when the weapon was last fired.
  uint32_t weapon_change_time;      ///< Level time when the weapon was last changed.

  pm_water_level_t old_water_level; ///< Water level from the previous frame.

  uint32_t hook_think_time;         ///< Level time when the hook think was last called.
  uint32_t hook_fire_time;          ///< Hook may fire again when time exceeds this.
  g_entity_t *hook_entity;          ///< The hook entity the client is attached to.
  bool hook_pull;                   ///< True if the client is currently pulling toward the hook.

  int16_t damage_armor;             ///< Damage absorbed by armor this frame.
  int16_t damage_health;            ///< Damage taken to health this frame.
  int16_t damage_inflicted;         ///< Damage inflicted on other clients this frame.

  int16_t max_armor;                ///< Maximum armor the client can carry.
  int16_t max_boost_health;         ///< Maximum health the client can be boosted to.

  float speed;                      ///< Horizontal speed after the last move.
  vec3_t angles;                    ///< Current aiming direction angles.
  vec3_t forward, right, up;        ///< Aiming direction vectors.
  vec3_t cmd_angles;                ///< Angles received in the last movement command.
  vec3_t kick_angles;               ///< View kick angles accumulated this frame.

  bool snap_angles;                 ///< One-shot flag to snap the view angles on the next frame.

  uint32_t respawn_time;            ///< Client may respawn when time exceeds this.
  uint32_t respawn_protection_time; ///< Respawn protection expires at this time.
  uint32_t ground_time;             ///< Level time when the client last touched the ground.
  uint32_t boost_time;              ///< Falling damage becomes eligible when time exceeds this.
  uint32_t drown_time;              ///< Drowning damage becomes eligible when time exceeds this.
  uint32_t sizzle_time;             ///< Sizzle damage becomes eligible when time exceeds this.
  uint32_t land_time;               ///< Landing event fires when time exceeds this.
  uint32_t jump_time;               ///< Client may jump when time exceeds this.
  uint32_t pain_time;               ///< Pain sound may play when time exceeds this.
  uint32_t footstep_time;           ///< Footstep sound plays when time exceeds this.
  uint32_t animation1_time;         ///< Primary animation may update when time exceeds this.
  uint32_t animation2_time;         ///< Secondary animation may update when time exceeds this.
  uint32_t grenade_time;            ///< Held grenade detonates when time exceeds this.
  uint32_t grenade_hold_time;       ///< Level time when the client began holding a primed grenade.
  uint32_t grenade_hold_frame;      ///< Frame number when the grenade pin was pulled.
  g_entity_t *held_grenade;         ///< The grenade entity the client is currently holding.

  uint32_t pickup_msg_time;         ///< Pickup message is displayed until time exceeds this.
  const g_item_t *last_pickup;      ///< Last usable item picked up.
  uint32_t chat_time;               ///< Client may chat when time exceeds this.

  uint32_t quad_damage_time;        ///< Quad damage is active while time is less than this.
  uint32_t quad_countdown_time;     ///< Quad damage countdown warning threshold.
  uint32_t quad_attack_time;        ///< Quad attack sound plays when time exceeds this.

  g_client_t *chase_target;         ///< Client being chased in spectator mode.
  g_client_t *old_chase_target;     ///< Previously chased client.

  const g_item_t *last_dropped;     ///< Last dropped item, used for variable expansion.

  bool show_scores;                 ///< True if the scoreboard layout flag should be set.
  uint32_t scores_time;             ///< Scores may be sent when time exceeds this.

  uint32_t regen_time;              ///< Next regeneration tick time.
  uint32_t tech_sound_time;         ///< Next time a tech powerup sound may play.
};

typedef struct g_client_s g_client_t;

/**
 * @brief The g_entity_s structure extends the server stub to
 * provide all of the state management the game module requires.
 */
struct g_entity_s {
  const cm_entity_t *def;                                                              ///< Entity definition parsed from the BSP file.
  const char *classname;                                                               ///< Entity class name; guaranteed set through G_Spawn.
  const char *model;                                                                   ///< Model name; for SOLID_BSP entities this is the inline model name.
  entity_state_t s;                                                                    ///< Entity state written by the game and delta-compressed by the server.
  bool in_use;                                                                         ///< True if the entity is currently allocated and active.
  uint32_t sv_flags;                                                                   ///< Server-specific flags bitmask (e.g. SVF_NO_CLIENT).
  box3_t bounds;                                                                       ///< Game-set bounding box in entity-local space.
  box3_t abs_bounds;                                                                   ///< Server-set bounding box in world space; set by gi.LinkEntity.
  vec3_t size;                                                                         ///< Server-set entity size; set by gi.LinkEntity.
  solid_t solid;                                                                       ///< Solid type defining clipping behavior.
  g_entity_t *owner;                                                                   ///< Entity that spawned this one (e.g. player for projectiles).
  g_client_t *client;                                                                  ///< Non-null for entities 1..sv_max_clients.

  uint32_t spawn_flags;                                                                ///< Spawn flags (SF_ITEM_HOVER, etc.).
  uint32_t flags;                                                                      ///< Entity flags (FL_GOD_MODE, etc.).

  g_move_type_t move_type;                                                             ///< Physics move type.
  g_move_info_t move_info;                                                             ///< Physics move parameters and state.

  int32_t clip_mask;                                                                   ///< Clip mask (e.g. CONTENTS_MASK_CLIP_PROJECTILE).

  uint32_t timestamp;                                                                  ///< General-purpose timestamp.

  const char *target;                                                                  ///< Target name to fire when triggered.
  const char *target_name;                                                             ///< This entity's target name.
  const char *message;                                                                 ///< Message to print when triggered.
  const char *team;                                                                    ///< Team name for multi-entity grouping.

  g_entity_t *target_ent;                                                              ///< Cached pointer to the target entity.

  float speed, accel, decel;                                                           ///< Movement speed and acceleration parameters.
  vec3_t move_dir;                                                                     ///< Direction of movement derived from angles.
  vec3_t pos1, pos2;                                                                   ///< Start and end positions for movers.

  vec3_t velocity;                                                                     ///< Linear velocity.
  vec3_t avelocity;                                                                    ///< Angular velocity.

  float mass;                                                                          ///< Entity mass used for physics calculations.

  uint32_t next_think;                                                                 ///< Level time of the next Think invocation.
  void (*Think)(g_entity_t *ent);                                                      ///< Per-frame think callback.
  void (*Blocked)(g_entity_t *ent, g_entity_t *other);                                 ///< Called when a mover is blocked.
  void (*Touch)(g_entity_t *ent, g_entity_t *other, const cm_trace_t *trace);          ///< Called on entity contact.
  void (*Use)(g_entity_t *ent, g_entity_t *other, g_entity_t *activator);              ///< Called when triggered.
  void (*Pain)(g_entity_t *ent, g_entity_t *other, int16_t damage, int16_t knockback); ///< Called when damaged.
  void (*Die)(g_entity_t *ent, g_entity_t *attacker, uint32_t mod);                    ///< Called when health drops to zero.

  uint32_t touch_time;                                                                 ///< Cooldown timer for Touch events.
  uint32_t push_time;                                                                  ///< Time of the last push interaction.
  uint32_t ripple_time;                                                                ///< Time of the last water ripple.
  float ripple_size;                                                                   ///< Radius of the last water ripple.

  int16_t health;                                                                      ///< Current health.
  int16_t max_health;                                                                  ///< Maximum health.
  bool dead;                                                                           ///< True if the entity is dead.

  bool take_damage;                                                                    ///< True if the entity can receive damage.
  int16_t damage;                                                                      ///< Damage dealt on contact.
  int16_t knockback;                                                                   ///< Knockback applied on contact.
  float damage_radius;                                                                 ///< Radius for splash damage.
  int32_t count;                                                                       ///< General-purpose counter (usage varies by entity type).

  g_entity_t *enemy;                                                                   ///< Current enemy entity.
  g_entity_t *activator;                                                               ///< Entity that last activated/triggered this entity.
  g_entity_t *team_master;                                                             ///< First entity in a team chain.
  g_entity_t *team_next;                                                               ///< Next entity in the team chain.

  uint16_t sound;                                                                      ///< Looping ambient sound index.

  float wait;                                                                          ///< Time to wait between activations.
  float delay;                                                                         ///< Delay before firing targets after activation.
  float random;                                                                        ///< Random time added to the delay.

  cm_trace_t ground;                                                                   ///< Ground trace result from the last physics frame.

  int32_t water_type;                                                                  ///< Content type of water the entity is submerged in.
  pm_water_level_t water_level;                                                        ///< Current water immersion level.

  const g_item_t *item;                                                                ///< Item definition for bonus item entities.
  ai_node_id_t node;                                                                   ///< AI navigation node for item path tracking.
  bool move_node;                                                                      ///< True if the entity should advance along the item path.
};

typedef struct g_entity_s g_entity_t;

#include "game/game.h"

#endif /* __GAME_LOCAL_H__ */
