/*
 * Copyright(c) 1997-2001 id Software, Inc.
 * Copyright(c) 2002 The Quakeforge Project.
 * Copyright(c) 2006 Quetoo.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA  02111-1307, USA.
 */

#pragma once

#include "shared/shared.h"
#include "collision/cm_types.h"

/**
 * @brief Game protocol version (protocol minor version). To be incremented
 * whenever the game protocol changes.
 */
#define PROTOCOL_MINOR 1023

/**
 * @brief Game-specific server protocol commands. These are parsed directly by
 * the client game module.
 */
typedef enum {
  SV_CMD_SOUND = SV_CMD_CGAME,
  SV_CMD_MUZZLE_FLASH,
  SV_CMD_TEMP_ENTITY,
  SV_CMD_VIEW_KICK,
  SV_CMD_CENTER_PRINT,
  SV_CMD_SCORES,
  SV_CMD_SNAP_ANGLES,
} g_sv_packet_cmd_t;

/**
 * @brief Game-specific client protocol commands. These are parsed directly by
 * the game module.
 */
typedef enum {
  CL_CMD_EXAMPLE = CL_CMD_CGAME,
} g_cl_packet_cmd_t;

/**
 * @brief The name of the map list generated by the user interface.
 */
#define MAP_LIST_UI "maps.ui.lst"

/**
 * @brief Map list entries describe available gameplay parameters for a given map.
 */
typedef struct {

  /**
   * @brief Map file name.
   */
  char name[32];

  /**
   * @brief Descriptive map title shown in the UI.
   */
  char message[128];

  /**
   * @brief Override gravity, or 0 for default.
   */
  int32_t gravity;

  /**
   * @brief Override gameplay mode, or -1 for default.
   */
  int32_t gameplay;

  /**
   * @brief Override hook setting, or -1 for default.
   */
  int32_t hook;

  /**
   * @brief Override teams setting, or -1 for default.
   */
  int32_t teams;

  /**
   * @brief Number of teams, or 0 for default.
   */
  int32_t num_teams;

  /**
   * @brief Override techs setting, or -1 for default.
   */
  int32_t techs;

  /**
   * @brief Override CTF setting, or -1 for default.
   */
  int32_t ctf;

  /**
   * @brief Override frag limit, or 0 for default.
   */
  int32_t frag_limit;

  /**
   * @brief Override capture limit, or 0 for default.
   */
  int32_t capture_limit;

  /**
   * @brief Override time limit in minutes, or 0 for default.
   */
  float time_limit;

  /**
   * @brief Items to give to all players on spawn.
   */
  char give[MAX_STRING_CHARS];

  /**
   * @brief Background music track.
   */
  char music[MAX_STRING_CHARS];
} g_map_list_map_t;

/**
 * @brief ConfigStrings that are local to the game module.
 */
#define CS_GAMEPLAY        (CS_GAME + 0)  // gameplay string
#define CS_CTF             (CS_GAME + 1)  // is capture enabled?
#define CS_TEAM_INFO       (CS_GAME + 2)  // team info, separated by \ (name\color\name\color, etc)
#define CS_TIME            (CS_GAME + 3)  // map time
#define CS_HOOK_PULL_SPEED (CS_GAME + 4)  // hook speed
#define CS_MAX_CLIENTS     (CS_GAME + 5)  // max clients of server
#define CS_NUM_CLIENTS     (CS_GAME + 6)  // number of players in server
#define CS_NUM_TEAMS       (CS_GAME + 7)  // number of teams (0 - MAX_TEAMS)
#define CS_WEAPONS         (CS_GAME + 8)  // weapon list, for the change weapon UI
#define CS_NAV_EDIT        (CS_GAME + 9) // nav edit mode

/**
 * @brief Player state statistics (inventory, score, etc).
 */
typedef enum {
  STAT_AMMO,
  STAT_AMMO_ICON,
  STAT_AMMO_LOW,
  STAT_ARMOR,
  STAT_ARMOR_ICON,
  STAT_CAPTURES,
  STAT_CHASE,
  STAT_DAMAGE_ARMOR,
  STAT_DAMAGE_HEALTH,
  STAT_DAMAGE_INFLICT,
  STAT_FRAGS,
  STAT_DEATHS,
  STAT_HEALTH,
  STAT_HEALTH_ICON,
  STAT_CARRYING_FLAG,
  STAT_PICKUP_ICON,
  STAT_PICKUP_STRING,
  STAT_QUAD_TIME,
  STAT_SCORES,
  STAT_SPECTATOR,
  STAT_TEAM,
  STAT_TIME,
  STAT_WEAPON,
  STAT_WEAPON_ICON,
  STAT_WEAPON_TAG,
  STAT_WEAPONS,
  STAT_TECH_ICON
} g_stat_t;

/**
 * @brief Forces a statistic field to be re-sent, even if the value has not changed.
 */
#define STAT_TOGGLE_BIT 0x4000

/**
 * @brief Muzzle flashes are bound to the entity that created them. This allows
 * the protocol to forego sending the origin and angles for the effect, as they
 * can be inferred from the referenced entity.
 */
typedef enum {
  MZ_BLASTER,
  MZ_SHOTGUN,
  MZ_SUPER_SHOTGUN,
  MZ_MACHINEGUN,
  MZ_GRENADE_LAUNCHER,
  MZ_ROCKET_LAUNCHER,
  MZ_HYPERBLASTER,
  MZ_LIGHTNING,
  MZ_RAILGUN,
  MZ_BFG10K,
  MZ_LOGOUT,
} g_muzzle_flash_t;

/**
 * @brief Temporary entities are positional events that are not explicitly
 * bound to a game entity (g_entity_t). Examples are explosions, certain weapon
 * trails and other short-lived effects.
 */
typedef enum {
  TE_TELEPORT,
  TE_BLASTER,
  TE_TRACER,
  TE_BULLET,
  TE_BLOOD,
  TE_SPARKS,
  TE_HYPERBLASTER,
  TE_LIGHTNING_DISCHARGE,
  TE_RAIL,
  TE_EXPLOSION,
  TE_BUBBLES,
  TE_BFG_LASER,
  TE_BFG,
  TE_GIB,
  TE_RIPPLE,
  TE_HOOK_IMPACT,
  TE_AI_NODE,
  TE_AI_NODE_LINK
} g_temp_entity_t;

/**
 * @brief Sound playback flags.
 */
#define SOUND_ENTITY    (1 << 0)
#define SOUND_ORIGIN    (1 << 1)
#define SOUND_ATTEN     (1 << 2)
#define SOUND_PITCH     (1 << 3)

/**
 * @brief Sound playback dispatch. Sounds may be associated with an entity, or simply positioned.
 */
typedef struct {

  /**
   * @brief ConfigString index of the sample to play.
   */
  int32_t index;

  /**
   * @brief Entity to bind the sound to for positioning.
   */
  const struct g_entity_s *entity;

  /**
   * @brief Sound origin, takes precedence over the entity origin.
   */
  const vec3_t *origin;

  /**
   * @brief Attenuation model.
   */
  sound_atten_t atten;

  /**
   * @brief Pitch shift in tones; 8 tones per octave.
   */
  int8_t pitch;
} g_play_sound_t;

/**
 * @brief Player scores are transmitted as binary to the client game module.
 */
typedef struct {

  /**
   * @brief Client number.
   */
  uint16_t client;

  /**
   * @brief Round-trip latency in milliseconds.
   */
  int16_t ping;

  /**
   * @brief Team or player color hue.
   */
  int16_t color;

  /**
   * @brief Frag or point score.
   */
  int16_t score;

  /**
   * @brief Number of flag captures.
   */
  int16_t captures;

  /**
   * @brief Number of deaths.
   */
  uint16_t deaths;

  /**
   * @brief Score flags (SCORE_CTF_FLAG, etc.).
   */
  uint8_t flags;

  /**
   * @brief Team index.
   */
  uint8_t team;
} g_score_t;

/**
 * @brief Player scores flags.
 */
#define SCORE_CTF_FLAG  (1 << 0)
#define SCORE_SPECTATOR (1 << 2)
#define SCORE_AGGREGATE (1 << 3)

/**
 * @brief Game-specific entity events.
 */
typedef enum {
  EV_CLIENT_TELEPORT = EV_GAME,
  EV_CLIENT_DROWN,
  EV_CLIENT_FALL,
  EV_CLIENT_FALL_FAR,
  EV_CLIENT_FOOTSTEP,
  EV_CLIENT_GURP,
  EV_CLIENT_JUMP,
  EV_CLIENT_LAND,
  EV_CLIENT_SIZZLE,
  EV_ITEM_RESPAWN,
  EV_ITEM_PICKUP,
} g_entity_event_t;

/**
 * @brief Game-specific entity state effects.
 */
#define EF_ROTATE     (EF_GAME << 0) // rotate on z
#define EF_BOB        (EF_GAME << 1) // bob on z
#define EF_INACTIVE   (EF_GAME << 2) // inactive icon for when input is not going to game
#define EF_BEAM       (EF_GAME << 3) // overloads old_origin for endpoint
#define EF_CORPSE     (EF_GAME << 4) // to differentiate own corpse from self
#define EF_RESPAWN    (EF_GAME << 5) // yellow shell
#define EF_QUAD       (EF_GAME << 6) // blue-green shell
#define EF_CTF_RED    (EF_GAME << 7) // carrying the red flag
#define EF_CTF_BLUE   (EF_GAME << 8) // carrying the blue flag
#define EF_CTF_YELLOW (EF_GAME << 9) // carrying the yellow flag
#define EF_CTF_GREEN  (EF_GAME << 10) // carrying the green flag
#define EF_DESPAWN    (EF_GAME << 11) // translucent
#define EF_LIGHT      (EF_GAME << 12) // colored light
#define EF_TEAM_TINT  (EF_GAME << 13) // tint by the team color provided

#define EF_CTF_MASK   (EF_CTF_RED | EF_CTF_BLUE | EF_CTF_YELLOW | EF_CTF_GREEN)

/**
 * @brief The lightning gun overrides animation1 to inform the client what
 * kind of trail to render.
 */
#define LIGHTNING_NO_HIT    0
#define LIGHTNING_SOLID_HIT 1

/**
 * @brief Game-specific entity state trails.
 */
typedef enum {
  TRAIL_BLASTER = TRAIL_GAME,
  TRAIL_GRENADE,
  TRAIL_ROCKET,
  TRAIL_HYPERBLASTER,
  TRAIL_LIGHTNING,
  TRAIL_BFG,
  TRAIL_TELEPORTER,
  TRAIL_GIB,
  TRAIL_FIREBALL,
  TRAIL_HOOK,
  TRAIL_PLAYER_SPAWN
} g_entity_trail_t;

/**
 * @brief Scoreboard background color hues.
 */
#define TEAM_COLOR_RED    color_hue_red
#define TEAM_COLOR_BLUE   color_hue_blue
#define TEAM_COLOR_YELLOW color_hue_yellow
#define TEAM_COLOR_GREEN  color_hue_green

/**
 * @brief Team ID
 */
typedef enum {
  TEAM_NONE = -1,
  TEAM_RED,
  TEAM_BLUE,
  TEAM_YELLOW,
  TEAM_GREEN,

  MAX_TEAMS
} g_team_id_t;

/**
 * @brief Entity state model number to indicate that the entity is a client.
 * When this is set, the model should be resolved from `CS_CLIENTS`.
 */
#define MODEL_CLIENT 0xff

/**
 * @brief Weapon handedness.
 */
typedef enum {
  HAND_CENTER,
  HAND_RIGHT,
  HAND_LEFT
} g_hand_t;

/**
 * @brief Game modes. These are selected via `g_gameplay` and sent to client via ConfigString.
 */
typedef enum {
  GAME_DEATHMATCH,
  GAME_INSTAGIB,
  GAME_ARENA
} g_gameplay_t;

/**
 * @brief Hook style.
 */
typedef enum {
  HOOK_PULL,
  HOOK_SWING_MANUAL,
  HOOK_SWING_AUTO
} g_hook_style_t;

/**
 * @brief Item types.
 */
typedef enum {
  ITEM_AMMO,
  ITEM_ARMOR,
  ITEM_FLAG,
  ITEM_HEALTH,
  ITEM_POWERUP,
  ITEM_WEAPON,
  ITEM_TECH,

  ITEM_TOTAL
} g_item_type_t;

/**
 * @brief Weapon tags to inform the client game which weapon the player wields and
 * the order of the weapon switcher.
 */
typedef enum {
  WEAPON_NONE,

  WEAPON_BLASTER,
  WEAPON_SHOTGUN,
  WEAPON_SUPER_SHOTGUN,
  WEAPON_MACHINEGUN,
  WEAPON_HAND_GRENADE,
  WEAPON_GRENADE_LAUNCHER,
  WEAPON_ROCKET_LAUNCHER,
  WEAPON_HYPERBLASTER,
  WEAPON_LIGHTNING,
  WEAPON_RAILGUN,
  WEAPON_BFG10K,

  WEAPON_TOTAL
} g_weapon_tag_t;

/**
 * @brief Weapon flags provide hints to indicate weapon use.
 */
typedef enum {
  WF_PROJECTILE  = (1 << 0),
  WF_HITSCAN     = (1 << 1),
  WF_TIMED       = (1 << 2),
  WF_EXPLOSIVE   = (1 << 3),
  WF_SHORT_RANGE = (1 << 4),
  WF_MED_RANGE   = (1 << 5),
  WF_LONG_RANGE  = (1 << 6)
} g_weapon_flags_t;

/**
 * @brief Ammunition types.
 */
typedef enum {
  AMMO_SHELLS,
  AMMO_BULLETS,
  AMMO_GRENADES,
  AMMO_ROCKETS,
  AMMO_CELLS,
  AMMO_BOLTS,
  AMMO_SLUGS,
  AMMO_NUKES,

  AMMO_TOTAL
} g_ammo_t;

/**
 * @brief Armor types.
 */
typedef enum {
  ARMOR_SHARD,
  ARMOR_JACKET,
  ARMOR_COMBAT,
  ARMOR_BODY,

  ARMOR_TOTAL
} g_armor_t;

/**
 * @brief Armor attributes.
 */
typedef struct {

  /**
   * @brief Armor type tag.
   */
  g_armor_t tag;

  /**
   * @brief Protection fraction against normal damage.
   */
  float normal_protection;

  /**
   * @brief Protection fraction against energy damage.
   */
  float energy_protection;
} g_armor_info_t;

/**
 * @brief Health types.
 */
typedef enum {
  HEALTH_SMALL,
  HEALTH_MEDIUM,
  HEALTH_LARGE,
  HEALTH_MEGA,

  HEALTH_TOTAL
} g_health_t;

/**
 * @brief Powerup types.
 */
typedef enum {
  POWERUP_QUAD,
  POWERUP_ADRENALINE,

  POWERUP_TOTAL
} g_powerup_t;

/**
 * @brief Tech types.
 */
typedef enum {
  TECH_HASTE,
  TECH_REGEN,
  TECH_RESIST,
  TECH_STRENGTH,
  TECH_VAMPIRE,

  TECH_TOTAL
} g_tech_t;

#if defined(__GAME_LOCAL_H__)

/**
 * @brief This file will define the game-visible definitions of g_client_t
 * and g_entity_t. They are much larger than the server-visible definitions,
 * which are intentionally truncated stubs.
 */
typedef struct g_client_s g_client_t;
typedef struct g_entity_s g_entity_t;

/**
 * @brief Spawn flags for g_entity_t are set in the level editor.
 */
#define SF_ITEM_TRIGGER  0x00000001
#define SF_ITEM_NO_TOUCH 0x00000002
#define SF_ITEM_HOVER    0x00000004

/**
 * @brief These spawn flags are actually set by the game module on entities
 * that are programmatically instantiated.
 */
#define SF_ITEM_DROPPED      0x00010000
#define SF_ITEM_TARGETS_USED 0x00020000

/**
 * @brief Entity flags (g_entity_locals.flags). These again are mostly for
 * backwards compatibility with Quake II.
 */
#define FL_FLY        0x00000001
#define FL_SWIM       0x00000002  // implied immunity to drowning
#define FL_GOD_MODE   0x00000004
#define FL_TEAM_SLAVE 0x00000008  // not the first on the team

/**
 * @brief Move types govern the physics dispatch in G_RunEntity.
 */
typedef enum {
  MOVE_TYPE_NONE,
  MOVE_TYPE_NO_CLIP,
  MOVE_TYPE_PUSH,
  MOVE_TYPE_STOP,

  MOVE_TYPE_WALK,
  MOVE_TYPE_FLY,
  MOVE_TYPE_BOUNCE
} g_move_type_t;

/**
 * @brief A synonym for readability; MOVE_TYPE_THINK implies that the entity's
 * Think function will update its origin and handle other interactions.
 */
#define MOVE_TYPE_THINK MOVE_TYPE_NONE

/**
 * @brief Items are touchable entities that players visit to acquire inventory.
 */
typedef struct g_item_s {

  /**
   * @brief Entity classname used for map spawning.
   */
  const char *classname;

  /**
   * @brief Called when a player touches the item; return false to prevent pickup.
   */
  bool (*Pickup)(g_client_t *cl, g_entity_t *it);

  /**
   * @brief Called when the item is activated from inventory.
   */
  void (*Use)(g_client_t *cl, const struct g_item_s *item);

  /**
   * @brief Called to drop the item; returns the dropped entity or NULL.
   */
  g_entity_t *(*Drop)(g_client_t *cl, const struct g_item_s *item);

  /**
   * @brief Called every frame for a player holding this weapon.
   */
  void (*Think)(g_client_t *cl);

  /**
   * @brief Name of the ammo item this weapon consumes.
   */
  const char *ammo;

  /**
   * @brief Sound to play on pickup.
   */
  const char *pickup_sound;

  /**
   * @brief World model path.
   */
  const char *model;

  /**
   * @brief Entity effect flags on the pickup entity.
   */
  uint32_t effects;

  /**
   * @brief Icon image path, used on HUD and in pickup messages.
   */
  const char *icon;

  /**
   * @brief Display name.
   */
  const char *name;

  /**
   * @brief Amount provided or consumed, depending on type.
   */
  uint16_t quantity;

  /**
   * @brief Maximum amount the player can carry (ammo/armor).
   */
  uint16_t max;

  /**
   * @brief Type-specific tag (e.g. g_weapon_tag_t, g_ammo_t).
   */
  uint16_t tag;

  /**
   * @brief Type-specific flags (e.g. g_weapon_flags_t).
   */
  uint16_t flags;

  /**
   * @brief Item type category.
   */
  g_item_type_t type;

  /**
   * @brief Relative priority used by AI for item selection.
   */
  float priority;

  /**
   * @brief Space-separated list of assets to precache.
   */
  const char *precaches;

  /**
   * @brief Index in the global item list; calculated at init.
   */
  uint16_t index;

  /**
   * @brief Pointer to the ammo item; calculated at init.
   */
  const struct g_item_s *ammo_item;

  /**
   * @brief Precached icon image index; calculated at init.
   */
  uint16_t icon_index;

  /**
   * @brief Precached model index; calculated at init.
   */
  uint16_t model_index;

  /**
   * @brief Precached pickup sound index; calculated at init.
   */
  uint16_t pickup_sound_index;
} g_item_t;

#define EOFS(x) (ptrdiff_t) &(((g_entity_t *) 0)->x)

/**
 * @brief Movement states.
 */
typedef enum {
  MOVE_STATE_BOTTOM,
  MOVE_STATE_GOING_UP,
  MOVE_STATE_GOING_DOWN,
  MOVE_STATE_TOP,
} g_move_state_t;

/**
 * @brief Physics parameters and think functions for entities which move.
 */
typedef struct {

  /**
   * @brief Starting origin.
   */
  vec3_t start_origin;

  /**
   * @brief Starting angles.
   */
  vec3_t start_angles;

  /**
   * @brief Ending origin.
   */
  vec3_t end_origin;

  /**
   * @brief Ending angles.
   */
  vec3_t end_angles;

  /**
   * @brief Sound played when movement begins.
   */
  uint16_t sound_start;

  /**
   * @brief Sound played while moving.
   */
  uint16_t sound_middle;

  /**
   * @brief Sound played when movement ends.
   */
  uint16_t sound_end;

  /**
   * @brief Acceleration rate.
   */
  float accel;

  /**
   * @brief Constant travel speed.
   */
  float speed;

  /**
   * @brief Deceleration rate.
   */
  float decel;

  /**
   * @brief Total distance to travel.
   */
  float distance;

  /**
   * @brief Time to wait at each end before reversing.
   */
  float wait;

  /**
   * @brief Current movement state.
   */
  g_move_state_t state;

  /**
   * @brief Current target destination.
   */
  vec3_t dest;

  /**
   * @brief Direction of travel.
   */
  vec3_t dir;

  /**
   * @brief Current movement speed.
   */
  float current_speed;

  /**
   * @brief Number of frames the move uses constant speed.
   */
  int32_t const_frames;

  /**
   * @brief Number of frames the move is accelerating.
   */
  int32_t accel_frames;

  /**
   * @brief Number of frames the move is decelerating.
   */
  int32_t decel_frames;

  /**
   * @brief Callback invoked when the move completes.
   */
  void (*Done)(g_entity_t *);
} g_move_info_t;

#define NUM_GIB_MODELS 4
#define NUM_GIB_SOUNDS 3

/**
 * @brief This structure holds references to frequently accessed media.
 */
typedef struct {
  struct g_media_items_t {
    const g_item_t *ammo[AMMO_TOTAL];
    const g_item_t *armor[ARMOR_TOTAL];
    const g_item_t *flags[MAX_TEAMS];
    const g_item_t *health[HEALTH_TOTAL];
    const g_item_t *powerups[POWERUP_TOTAL];
    const g_item_t *weapons[WEAPON_TOTAL];
    const g_item_t *techs[TECH_TOTAL];
  } items;

  struct g_media_models_t {
    uint16_t gibs[NUM_GIB_MODELS];

    uint16_t grenade;
    uint16_t rocket;
    uint16_t hook;

    uint16_t fireball;
  } models;

  struct g_media_sounds_t {
    uint16_t gib_hits[NUM_GIB_SOUNDS];

    uint16_t bfg_hit;
    uint16_t bfg_prime;
    uint16_t grenade_hit;
    uint16_t grenade_throw;
    uint16_t rocket_fly;
    uint16_t lightning_fly;
    uint16_t quad_attack;
    uint16_t quad_expire;

    uint16_t hook_fire;
    uint16_t hook_hit;
    uint16_t hook_pull;
    uint16_t hook_fly;
    uint16_t hook_detach;
    uint16_t hook_gibhit;

    uint16_t teleport;

    uint16_t water_in;
    uint16_t water_out;

    uint16_t weapon_no_ammo;
    uint16_t weapon_switch;

    uint16_t countdown[11];

    uint16_t roar;

    uint16_t techs[TECH_TOTAL];

    uint16_t chat;
  } sounds;

  struct g_media_images_t {
    uint16_t health;
  } images;
} g_media_t;

/**
 * @brief A list of spawn point entities available for player spawning.
 */
typedef struct {

  /**
   * @brief Number of spawn point entities.
   */
  uint32_t count;

  /**
   * @brief Array of spawn point entity pointers.
   */
  g_entity_t **spots;
} g_spawn_points_t;

/**
 * @brief The main structure for all world management. This is cleared at each
 * level load.
 */
typedef struct {

  /**
   * @brief Current server frame number.
   */
  uint32_t frame_num;

  /**
   * @brief Level time in milliseconds.
   */
  uint32_t time;

  /**
   * @brief Descriptive map name (e.g. "Stress Fractures").
   */
  char title[MAX_STRING_CHARS];

  /**
   * @brief Short server map name (e.g. "fractures").
   */
  char name[MAX_QPATH];

  /**
   * @brief Gravity override.
   */
  int16_t gravity;

  /**
   * @brief Active gameplay mode.
   */
  g_gameplay_t gameplay;

  /**
   * @brief True if team play is active.
   */
  bool teams;

  /**
   * @brief True if capture the flag is active.
   */
  bool ctf;

  /**
   * @brief True if tech powerups are enabled.
   */
  bool techs;

  /**
   * @brief True if the grappling hook is enabled.
   */
  bool hook;

  /**
   * @brief Number of active teams.
   */
  int32_t num_teams;

  /**
   * @brief Map-specified hook allowance, used for voting and restarts.
   */
  int32_t hook_map;

  /**
   * @brief Map-specified techs allowance.
   */
  int32_t techs_map;

  /**
   * @brief Frag limit; game ends when a player reaches this.
   */
  int32_t frag_limit;

  /**
   * @brief Capture limit; game ends when a team reaches this.
   */
  int32_t capture_limit;

  /**
   * @brief Time limit in minutes; game ends when exceeded.
   */
  int32_t time_limit;

  /**
   * @brief Items to give all players on spawn.
   */
  char give[MAX_STRING_CHARS];

  /**
   * @brief Background music track.
   */
  char music[MAX_STRING_CHARS];

  /**
   * @brief Level time when scores were last updated.
   */
  uint32_t scores_time;

  /**
   * @brief Level time when intermission began.
   */
  uint32_t intermission_time;

  /**
   * @brief Camera origin during intermission.
   */
  vec3_t intermission_origin;

  /**
   * @brief Camera angles during intermission.
   */
  vec3_t intermission_angle;

  /**
   * @brief Next map name to load after intermission.
   */
  const char *next_map;

  /**
   * @brief Entity currently being processed by G_RunFrame.
   */
  g_entity_t *current_entity;

  /**
   * @brief Global spawn points (used in non-team modes).
   */
  g_spawn_points_t spawn_points;
} g_level_t;

/**
 * @brief Means of death.
 */
 typedef enum {
  MOD_UNKNOWN,
  MOD_BLASTER,
  MOD_SHOTGUN,
  MOD_SUPER_SHOTGUN,
  MOD_MACHINEGUN,
  MOD_GRENADE,
  MOD_GRENADE_SPLASH,
  MOD_ROCKET,
  MOD_ROCKET_SPLASH,
  MOD_HYPERBLASTER,
  MOD_HYPERBLASTER_CLIMB,
  MOD_LIGHTNING,
  MOD_LIGHTNING_DISCHARGE,
  MOD_RAILGUN,
  MOD_BFG_LASER,
  MOD_BFG_BLAST,
  MOD_WATER,
  MOD_SLIME,
  MOD_LAVA,
  MOD_CRUSH,
  MOD_TELEFRAG,
  MOD_FALLING,
  MOD_SUICIDE,
  MOD_EXPLOSIVE,
  MOD_TRIGGER_HURT,
  MOD_HANDGRENADE,
  MOD_HANDGRENADE_SPLASH,
  MOD_HANDGRENADE_SUICIDE,
  MOD_HANDGRENADE_KAMIKAZE,
  MOD_FIREBALL,
  MOD_HOOK,
  MOD_ACT_OF_GOD,
  MOD_FRIENDLY_FIRE = 0x8000000
} g_means_of_death;

/**
 * @brief Damage flags. These can be and often are combined.
 */
#define DMG_RADIUS   0x1  // damage was indirect
#define DMG_ENERGY   0x2  // damage is from an energy based weapon
#define DMG_BULLET   0x4  // damage is from a bullet
#define DMG_NO_ARMOR 0x8  // armor does not protect from this damage
#define DMG_NO_GOD   0x10  // armor and god mode have no effect

/**
 * @brief Damage parameters for G_Damage.
 */
typedef struct {

 /**
  * @brief Entity receiving the damage.
  */
	g_entity_t *target;

 /**
  * @brief Entity that dealt the damage (projectile, explosion, etc.).
  */
	g_entity_t *inflictor;

 /**
  * @brief Entity responsible for the damage (player, etc.).
  */
	g_entity_t *attacker;

 /**
  * @brief Direction the damage came from.
  */
	vec3_t dir;

 /**
  * @brief World point where the damage was applied.
  */
	vec3_t point;

 /**
  * @brief Surface normal at the damage point.
  */
	vec3_t normal;

 /**
  * @brief Amount of damage to apply.
  */
	int32_t damage;

 /**
  * @brief Knockback force to apply.
  */
	int32_t knockback;

 /**
  * @brief Damage flags (DMG_RADIUS, DMG_ENERGY, etc.).
  */
	int32_t flags;

 /**
  * @brief Means of death identifier.
  */
	g_means_of_death mod;
} g_damage_t;

/**
 * @brief The name for the CTF skin used in team games.
 */
#define DEFAULT_TEAM_SKIN "ctf"

/**
 * @brief There are four teams in the default game module.
 */
typedef struct {

  /**
   * @brief Team identifier, used for comparison instead of pointer equality.
   */
  g_team_id_t id;

  /**
   * @brief Short team name for HUD display.
   */
  char name[16];

  /**
   * @brief Team skin name.
   */
  char skin[32];

  /**
   * @brief Flag entity classname.
   */
  char flag[32];

  /**
   * @brief Spawn point classname.
   */
  char spawn[32];

  /**
   * @brief Team player colors.
   */
  color_t shirt, pants, helmet;

  /**
   * @brief Team color hue.
   */
  int16_t color;

  /**
   * @brief Entity effect for the team flag.
   */
  int16_t effect;

  /**
   * @brief Team score.
   */
  int16_t score;

  /**
   * @brief Team capture count.
   */
  int16_t captures;

  /**
   * @brief Spawn points for this team.
   */
  g_spawn_points_t spawn_points;

  /**
   * @brief The team's flag entity.
   */
  g_entity_t *flag_entity;
} g_team_t;

/**
 * @brief The default player model
 */
#define DEFAULT_USER_MODEL "qforcer"

/**
 * @brief The default player skin
 */
#define DEFAULT_USER_SKIN "default"

/**
 * @brief The default user info string (name and skin).
 */
#define DEFAULT_USER_INFO "\\name\\newbie\\skin\\" DEFAULT_USER_MODEL "/" DEFAULT_USER_SKIN

/**
 * @brief The full length of a net name, in bytes (including non-printables).
 */
#define MAX_NET_NAME 64

/**
 * @brief The maximum printable length of a net name.
 */
#define MAX_NET_NAME_PRINTABLE 15

/**
 * @brief This structure contains client data that persists over multiple spawns.
 */
typedef struct {

  /**
   * @brief Frame number when the client first entered the game.
   */
  uint32_t first_frame;

  /**
   * @brief Raw user info key-value string.
   */
  char user_info[MAX_INFO_STRING_STRING];

  /**
   * @brief Display name.
   */
  char net_name[MAX_NET_NAME];

  /**
   * @brief Player model/skin path.
   */
  char skin[MAX_QPATH];

  /**
   * @brief Weapon handedness preference.
   */
  g_hand_t hand;

  /**
   * @brief Non-zero if weapons should auto-switch on pickup.
   */
  uint16_t auto_switch;

  /**
   * @brief The player's selected hook style.
   */
  g_hook_style_t hook_style;

  /**
   * @brief Current team assignment.
   */
  g_team_t *team;

  /**
   * @brief Player effect color hue.
   */
  int16_t color;

  /**
   * @brief Player clothing colors.
   */
  color_t shirt, pants, helmet;

  /**
   * @brief Current score.
   */
  int16_t score;

  /**
   * @brief Number of flag captures.
   */
  int16_t captures;

  /**
   * @brief Number of deaths.
   */
  uint16_t deaths;

  /**
   * @brief True if the player has admin privileges.
   */
  bool admin;

  /**
   * @brief True if the player is a spectator.
   */
  bool spectator;

  /**
   * @brief True if the player is muted.
   */
  bool muted;
} g_client_persistent_t;

/**
 * @brief This structure is cleared on each spawn, with the persistent structure
 * explicitly copied over to preserve team membership, etc. This structure
 * extends the server-visible definition to provide all of the state management
 * the game module requires.
 */
struct g_client_s {

  /**
   * @brief The entity bound to this client.
   */
  g_entity_t *entity;

  /**
   * @brief Player state communicated to clients by the server.
   */
  player_state_t ps;

  /**
   * @brief Current round-trip latency in milliseconds.
   */
  uint32_t ping;

  /**
   * @brief Raw user info key-value string.
   */
  char user_info[MAX_INFO_STRING_STRING];

  /**
   * @brief True if this client slot is currently active.
   */
  bool in_use;

  /**
   * @brief Non-null if this client is a bot.
   */
  struct ai_s *ai;

  /**
   * @brief Data that persists across respawns.
   */
  g_client_persistent_t persistent;

  /**
   * @brief Most recently received movement command.
   */
  pm_cmd_t cmd;

  /**
   * @brief Item inventory counts indexed by item index.
   */
  int16_t inventory[MAX_ITEMS];

  /**
   * @brief Currently active weapon.
   */
  const g_item_t *weapon;

  /**
   * @brief Previously active weapon.
   */
  const g_item_t *prev_weapon;

  /**
   * @brief Weapon currently being switched to.
   */
  const g_item_t *next_weapon;

  /**
   * @brief Inventory index of the current weapon's ammo.
   */
  uint16_t ammo_index;

  /**
   * @brief Current frame button state.
   */
  uint32_t buttons;

  /**
   * @brief Previous frame button state.
   */
  uint32_t old_buttons;

  /**
   * @brief Buttons pressed this frame (edge-triggered).
   */
  uint32_t latched_buttons;

  /**
   * @brief Level time when the weapon think was last called.
   */
  uint32_t weapon_think_time;

  /**
   * @brief Weapon may fire again when time exceeds this.
   */
  uint32_t weapon_fire_time;

  /**
   * @brief Level time when the weapon was last fired.
   */
  uint32_t weapon_fired_time;

  /**
   * @brief Level time when the weapon was last changed.
   */
  uint32_t weapon_change_time;

  /**
   * @brief Water level from the previous frame.
   */
  pm_water_level_t old_water_level;

  /**
   * @brief Level time when the hook think was last called.
   */
  uint32_t hook_think_time;

  /**
   * @brief Hook may fire again when time exceeds this.
   */
  uint32_t hook_fire_time;

  /**
   * @brief The hook entity the client is attached to.
   */
  g_entity_t *hook_entity;

  /**
   * @brief True if the client is currently pulling toward the hook.
   */
  bool hook_pull;

  /**
   * @brief Damage absorbed by armor this frame.
   */
  int16_t damage_armor;

  /**
   * @brief Damage taken to health this frame.
   */
  int16_t damage_health;

  /**
   * @brief Damage inflicted on other clients this frame.
   */
  int16_t damage_inflicted;

  /**
   * @brief Maximum armor the client can carry.
   */
  int16_t max_armor;

  /**
   * @brief Maximum health the client can be boosted to.
   */
  int16_t max_boost_health;

  /**
   * @brief Horizontal speed after the last move.
   */
  float speed;

  /**
   * @brief Current aiming direction angles.
   */
  vec3_t angles;

  /**
   * @brief Aiming direction vectors.
   */
  vec3_t forward, right, up;

  /**
   * @brief Angles received in the last movement command.
   */
  vec3_t cmd_angles;

  /**
   * @brief View kick angles accumulated this frame.
   */
  vec3_t kick_angles;

  /**
   * @brief Client may respawn when time exceeds this.
   */
  uint32_t respawn_time;

  /**
   * @brief Respawn protection expires at this time.
   */
  uint32_t respawn_protection_time;

  /**
   * @brief Level time when the client last touched the ground.
   */
  uint32_t ground_time;

  /**
   * @brief Falling damage becomes eligible when time exceeds this.
   */
  uint32_t boost_time;

  /**
   * @brief Drowning damage becomes eligible when time exceeds this.
   */
  uint32_t drown_time;

  /**
   * @brief Sizzle damage becomes eligible when time exceeds this.
   */
  uint32_t sizzle_time;

  /**
   * @brief Landing event fires when time exceeds this.
   */
  uint32_t land_time;

  /**
   * @brief Client may jump when time exceeds this.
   */
  uint32_t jump_time;

  /**
   * @brief Pain sound may play when time exceeds this.
   */
  uint32_t pain_time;

  /**
   * @brief Footstep sound plays when time exceeds this.
   */
  uint32_t footstep_time;

  /**
   * @brief Primary animation may update when time exceeds this.
   */
  uint32_t animation1_time;

  /**
   * @brief Secondary animation may update when time exceeds this.
   */
  uint32_t animation2_time;

  /**
   * @brief Held grenade detonates when time exceeds this.
   */
  uint32_t grenade_time;

  /**
   * @brief Level time when the client began holding a primed grenade.
   */
  uint32_t grenade_hold_time;

  /**
   * @brief Frame number when the grenade pin was pulled.
   */
  uint32_t grenade_hold_frame;

  /**
   * @brief The grenade entity the client is currently holding.
   */
  g_entity_t *held_grenade;

  /**
   * @brief Pickup message is displayed until time exceeds this.
   */
  uint32_t pickup_msg_time;

  /**
   * @brief Last usable item picked up.
   */
  const g_item_t *last_pickup;

  /**
   * @brief Client may chat when time exceeds this.
   */
  uint32_t chat_time;

  /**
   * @brief Quad damage is active while time is less than this.
   */
  uint32_t quad_damage_time;

  /**
   * @brief Quad damage countdown warning threshold.
   */
  uint32_t quad_countdown_time;

  /**
   * @brief Quad attack sound plays when time exceeds this.
   */
  uint32_t quad_attack_time;

  /**
   * @brief Client being chased in spectator mode.
   */
  g_client_t *chase_target;

  /**
   * @brief Previously chased client.
   */
  g_client_t *old_chase_target;

  /**
   * @brief Last dropped item, used for variable expansion.
   */
  const g_item_t *last_dropped;

  /**
   * @brief True if the scoreboard layout flag should be set.
   */
  bool show_scores;

  /**
   * @brief Scores may be sent when time exceeds this.
   */
  uint32_t scores_time;

  /**
   * @brief Next regeneration tick time.
   */
  uint32_t regen_time;

  /**
   * @brief Next time a tech powerup sound may play.
   */
  uint32_t tech_sound_time;
};

typedef struct g_client_s g_client_t;

/**
 * @brief The g_entity_s structure extends the server stub to
 * provide all of the state management the game module requires.
 */
struct g_entity_s {

  /**
   * @brief Entity definition parsed from the BSP file.
   */
  const cm_entity_t *def;

  /**
   * @brief Entity class name; guaranteed set through G_Spawn.
   */
  const char *classname;

  /**
   * @brief Model name; for SOLID_BSP entities this is the inline model name.
   */
  const char *model;

  /**
   * @brief Entity state written by the game and delta-compressed by the server.
   */
  entity_state_t s;

  /**
   * @brief True if the entity is currently allocated and active.
   */
  bool in_use;

  /**
   * @brief Server-specific flags bitmask (e.g. SVF_NO_CLIENT).
   */
  uint32_t sv_flags;

  /**
   * @brief Game-set bounding box in entity-local space.
   */
  box3_t bounds;

  /**
   * @brief Server-set bounding box in world space; set by gi.LinkEntity.
   */
  box3_t abs_bounds;

  /**
   * @brief Server-set entity size; set by gi.LinkEntity.
   */
  vec3_t size;

  /**
   * @brief Solid type defining clipping behavior.
   */
  solid_t solid;

  /**
   * @brief Entity that spawned this one (e.g. player for projectiles).
   */
  g_entity_t *owner;

  /**
   * @brief Non-null for entities 1..sv_max_clients.
   */
  g_client_t *client;

  /**
   * @brief Spawn flags (SF_ITEM_HOVER, etc.).
   */
  uint32_t spawn_flags;

  /**
   * @brief Entity flags (FL_GOD_MODE, etc.).
   */
  uint32_t flags;

  /**
   * @brief Physics move type.
   */
  g_move_type_t move_type;

  /**
   * @brief Physics move parameters and state.
   */
  g_move_info_t move_info;

  /**
   * @brief Clip mask (e.g. CONTENTS_MASK_CLIP_PROJECTILE).
   */
  int32_t clip_mask;

  /**
   * @brief General-purpose timestamp.
   */
  uint32_t timestamp;

  /**
   * @brief Target name to fire when triggered.
   */
  const char *target;

  /**
   * @brief This entity's target name.
   */
  const char *target_name;

  /**
   * @brief Message to print when triggered.
   */
  const char *message;

  /**
   * @brief Team name for multi-entity grouping.
   */
  const char *team;

  /**
   * @brief Cached pointer to the target entity.
   */
  g_entity_t *target_ent;

  /**
   * @brief Movement speed and acceleration parameters.
   */
  float speed, accel, decel;

  /**
   * @brief Direction of movement derived from angles.
   */
  vec3_t move_dir;

  /**
   * @brief Start and end positions for movers.
   */
  vec3_t pos1, pos2;

  /**
   * @brief Linear velocity.
   */
  vec3_t velocity;

  /**
   * @brief Angular velocity.
   */
  vec3_t avelocity;

  /**
   * @brief Entity mass used for physics calculations.
   */
  float mass;

  /**
   * @brief Level time of the next Think invocation.
   */
  uint32_t next_think;

  /**
   * @brief Per-frame think callback.
   */
  void (*Think)(g_entity_t *ent);

  /**
   * @brief Called when a mover is blocked.
   */
  void (*Blocked)(g_entity_t *ent, g_entity_t *other);

  /**
   * @brief Called on entity contact.
   */
  void (*Touch)(g_entity_t *ent, g_entity_t *other, const cm_trace_t *trace);

  /**
   * @brief Called when triggered.
   */
  void (*Use)(g_entity_t *ent, g_entity_t *other, g_entity_t *activator);

  /**
   * @brief Called when damaged.
   */
  void (*Pain)(g_entity_t *ent, g_entity_t *other, int16_t damage, int16_t knockback);

  /**
   * @brief Called when health drops to zero.
   */
  void (*Die)(g_entity_t *ent, g_entity_t *attacker, uint32_t mod);

  /**
   * @brief Cooldown timer for Touch events.
   */
  uint32_t touch_time;

  /**
   * @brief Time of the last push interaction.
   */
  uint32_t push_time;

  /**
   * @brief Time of the last water ripple.
   */
  uint32_t ripple_time;

  /**
   * @brief Radius of the last water ripple.
   */
  float ripple_size;

  /**
   * @brief Current health.
   */
  int16_t health;

  /**
   * @brief Maximum health.
   */
  int16_t max_health;

  /**
   * @brief True if the entity is dead.
   */
  bool dead;

  /**
   * @brief True if the entity can receive damage.
   */
  bool take_damage;

  /**
   * @brief Damage dealt on contact.
   */
  int16_t damage;

  /**
   * @brief Knockback applied on contact.
   */
  int16_t knockback;

  /**
   * @brief Radius for splash damage.
   */
  float damage_radius;

  /**
   * @brief General-purpose counter (usage varies by entity type).
   */
  int32_t count;

  /**
   * @brief Current enemy entity.
   */
  g_entity_t *enemy;

  /**
   * @brief Entity that last activated/triggered this entity.
   */
  g_entity_t *activator;

  /**
   * @brief First entity in a team chain.
   */
  g_entity_t *team_master;

  /**
   * @brief Next entity in the team chain.
   */
  g_entity_t *team_next;

  /**
   * @brief Looping ambient sound index.
   */
  uint16_t sound;

  /**
   * @brief Time to wait between activations.
   */
  float wait;

  /**
   * @brief Delay before firing targets after activation.
   */
  float delay;

  /**
   * @brief Random time added to the delay.
   */
  float random;

  /**
   * @brief Ground trace result from the last physics frame.
   */
  cm_trace_t ground;

  /**
   * @brief Content type of water the entity is submerged in.
   */
  int32_t water_type;

  /**
   * @brief Current water immersion level.
   */
  pm_water_level_t water_level;

  /**
   * @brief Item definition for bonus item entities.
   */
  const g_item_t *item;

  /**
   * @brief AI navigation node for item path tracking.
   */
  ai_node_id_t node;

  /**
   * @brief True if the entity should advance along the item path.
   */
  bool move_node;
};

typedef struct g_entity_s g_entity_t;

#include "game/game.h"

#endif /* __GAME_LOCAL_H__ */
