#!/bin/bash

BINDIR=$(dirname "$0")

UPDATE=${BINDIR}/quetoo-update-1.0-SNAPSHOT.jar

if [ ! -f "${UPDATE}" ]; then
	UPDATE=${BINDIR}/quetoo-update-1.0-SNAPSHOT-small.jar;
fi

QUETOO_HOME=${BINDIR/Update.app*/}

java -jar "${UPDATE}" --gui --dir "${QUETOO_HOME}"
