# Makefile for Quake2World.app

APP = Quake2World.app
MACOS = ${APP}/Contents/MacOS
RESOURCES = ${APP}/Contents/Resources

${MACOS}/quake2world: ../src/main/quake2world
	install ../src/main/quake2world ${MACOS}/quake2world