/*
 * Copyright(c) 1997-2001 id Software, Inc.
 * Copyright(c) 2002 The Quakeforge Project.
 * Copyright(c) 2006 Quetoo.
 *
 * This program is free software; you can redistribute it and/or
 * modify it under the terms of the GNU General Public License
 * as published by the Free Software Foundation; either version 2
 * of the License, or (at your option) any later version.
 *
 * This program is distributed in the hope that it will be useful,
 * but WITHOUT ANY WARRANTY; without even the implied warranty of
 * MERCHANTABILITY or FITNESS FOR A PARTICULAR PURPOSE.
 *
 * See the GNU General Public License for more details.
 *
 * You should have received a copy of the GNU General Public License
 * along with this program; if not, write to the Free Software
 * Foundation, Inc., 59 Temple Place - Suite 330, Boston, MA 02111-1307, USA.
 */

#pragma once

#include <Objectively/Vector.h>

#include "shared/shared.h"
#include "collision/cm_types.h"
#include "bg_item.h"
#include "bg_pmove.h"
#include "game/common/bg_hook.h"
#include "game/game.h"

/**
 * @brief The name this module answers to: its directory under lib/quetoo, and
 * the gameName it advertises.
 */
#define GAME_NAME "race"

/**
 * @brief The movement a level runs when it names none and `g_movement` defers.
 */
#define G_MOVEMENT_DEFAULT PM_MOVEMENT_RACE

/**
 * @brief Game protocol version (protocol minor version). To be incremented
 * whenever the game protocol changes.
 */
#define PROTOCOL_MINOR 1055

/**
 * @brief Game-specific server protocol commands. These are parsed directly by
 * the client game module.
 */
/**
 * @brief Chat flags, carried opaquely by SV_CMD_CHAT. The engine does not interpret these; teams
 * are a game concern, as CS_TEAM_INFO is, so a module defines whatever channels it supports.
 */
#define CHAT_TEAM 0x01 // addressed to a team rather than to everyone

/**
 * @brief Voice channels, carried opaquely by CL_CMD_VOICE. The client game names them when it
 * transmits and the game answers for them when the server asks who may hear.
 */
#define VOICE_CHANNEL_ALL 0
#define VOICE_CHANNEL_TEAM 1

typedef enum {
  SV_CMD_SOUND = SV_CMD_CGAME,
  SV_CMD_MUZZLE_FLASH,
  SV_CMD_TEMP_ENTITY,
  SV_CMD_VIEW_KICK,
  SV_CMD_CENTER_PRINT,
  SV_CMD_SCORES,
  SV_CMD_SNAP_ANGLES,
  SV_CMD_RACE_BARRIERS, // [byte] count, [short] entity...: the barriers that pass this client
  SV_CMD_RACE_MILESTONE, // [byte] kind, [byte] number, [string] label, [long] time, [long] vs best, [long] vs record
} GameServerPacketCmd;

/**
 * @brief Game-specific client protocol commands. These are parsed directly by
 * the game module.
 */
typedef enum {
  CL_CMD_EXAMPLE = CL_CMD_CGAME,
} GameClientPacketCmd;

/**
 * @brief The name of the map list generated by the user interface.
 */
#define MAP_LIST_UI "maps.ui.lst"

/**
 * @brief ConfigStrings that are local to the game module.
 */
/**
 * @brief The maximum number of corpses standing at once. Each claims a slot of CS_CORPSES for
 * the client info it died wearing, so that it is unaffected by its owner changing skin or
 * disconnecting. The oldest is gibbed to make room when they are all spoken for.
 */
#define MAX_CORPSES 64

#define CS_GAMEPLAY        (CS_GAME + 0)  // gameplay string
#define CS_TEAM_INFO       (CS_GAME + 1)  // team info, separated by \ (name\color\name\color, etc)
#define CS_TIME            (CS_GAME + 2)  // map time
#define CS_NUM_TEAMS       (CS_GAME + 3)  // number of teams (0 - MAX_TEAMS)
#define CS_NAV_EDIT        (CS_GAME + 4)  // nav edit mode
#define CS_ITEM_SET        (CS_GAME + 5)  // active item set (GameItems)
#define CS_HOOK_PULL_SPEED (CS_GAME + 6)  // hook speed
#define CS_VOTE            (CS_GAME + 7)  // the vote in progress (bg_vote.h)
#define CS_RACE_COURSE     (CS_GAME + 8) // checkpoints\finishes\valid, for the HUD
#define CS_RACE_RECORDS    (CS_GAME + 9) // the top times under this movement, name\time pairs
#define CS_RACE_GHOST      (CS_GAME + 10) // the course record holder as a CS_CLIENTS string, for the ghost's skin
#define CS_NEXT_MAP        (CS_GAME + 11) // the intermission's map candidates and tally (bg_intermission.h)
#define CS_CORPSES         (CS_GAME + 12)  // one client info snapshot per corpse, MAX_CORPSES wide

/**
 * @brief Player state statistics (inventory, score, etc).
 */
typedef enum {
  STAT_ARMOR,
  STAT_CHASE,
  STAT_DAMAGE_ARMOR,
  STAT_DAMAGE_HEALTH,
  STAT_DAMAGE_INFLICT,
  STAT_DEATHS,
  STAT_FRAGS,
  STAT_HEALTH,
  STAT_INVISIBILITY_TIME,
  STAT_INVULNERABILITY_TIME,
  STAT_PICKUP,
  STAT_PING,
  STAT_QUAD_TIME,
  STAT_SCORES,
  STAT_SPECTATOR,
  STAT_TEAM,
  STAT_TIME,
  STAT_WEAPON,

  // racing, written by G_WriteStats_Race; the time is milliseconds split in two
  STAT_RACE_MODE,        // GameRaceMode
  STAT_RACE_RUN,         // GameRaceRunState
  STAT_RACE_TIME_LOW,
  STAT_RACE_TIME_HIGH,
  STAT_RACE_CHECKPOINTS, // reached; the total is on CS_RACE_COURSE
  STAT_RACE_FLAGS,       // GameRaceInvalid
  STAT_RACE_RUNS         // started on this map
} GameStat;

/**
 * @brief Forces a statistic field to be re-sent, even if the value has not changed.
 */
#define STAT_TOGGLE_BIT 0x4000

_Static_assert(STAT_RACE_RUNS < MAX_STATS, "the race stats must fit the stat array");

/**
 * @brief The most checkpoints a course may have, and likewise splits and
 * stages. A course is contiguous checkpoints 1 through N and at least one
 * finish; a start is optional, and so are splits and stages.
 */
#define RACE_MAX_CHECKPOINTS 64

// how many func_race_* brushes a level may have
#define RACE_MAX_BARRIERS 32

/**
 * @brief What a run just passed, reported to its racer as `SV_CMD_RACE_MILESTONE`
 * with the time and how it compares: against their own best, and against the
 * course record. A comparison with nothing to compare to is `RACE_MILESTONE_NO_DELTA`.
 */
typedef enum {
  RACE_MILESTONE_CHECKPOINT,
  RACE_MILESTONE_SPLIT,
  RACE_MILESTONE_STAGE,
} GameRaceMilestone;

#define RACE_MILESTONE_NO_DELTA INT32_MIN

// how many of a map's records CS_RACE_RECORDS carries, and the board shows
#define RACE_RECORDS_SHOWN 15

/**
 * @brief How a client is taking part. Spectating is derived from
 * `GameClientPersistent.spectator` rather than stored, so the two cannot
 * disagree; the other two are the client's choice and persist across respawns.
 */
typedef enum {
  RACE_MODE_RACE,      // finishes count, and the hook and noclip are refused
  RACE_MODE_PRACTICE,  // nothing counts, and everything is allowed
  RACE_MODE_SPECTATOR
} GameRaceMode;

/**
 * @brief Where a run is.
 */
typedef enum {
  RACE_RUN_IDLE,
  RACE_RUN_ACTIVE,
  RACE_RUN_FINISHED
} GameRaceRunState;

/**
 * @brief Why a finished run in race mode cannot count.
 */
typedef enum {
  RACE_INVALID_NOCLIP = 1 << 0,
  RACE_INVALID_MOVEMENT = 1 << 1 // the movement changed under the run
} GameRaceInvalid;

/**
 * @brief When a `trigger_race_start` begins the run, kept in the trigger's `count`.
 */
typedef enum {
  RACE_START_TOUCH, // on entering
  RACE_START_EXIT,  // on leaving
  RACE_START_JUMP   // on the first jump from inside
} GameRaceStartMode;

/**
 * @brief What a `func_race_*` brush is to a racer's movement, kept on the
 * entity so that `G_Race_ClipEntity` can tell one at a glance.
 */
typedef enum {
  RACE_BARRIER_NONE,
  RACE_BARRIER_GATE, // solid until the run's checkpoints satisfy it
  RACE_BARRIER_WALL  // solid from one side only
} GameRaceBarrier;

/**
 * @brief When a `func_race_checkpoint_gate` opens.
 */
typedef enum {
  RACE_GATE_AT_LEAST, // once the checkpoint has been reached
  RACE_GATE_EXACT     // only while it is the last one reached
} GameRaceGateMode;

typedef struct {
  uint16_t checkpoint;
  GameRaceGateMode mode;
  bool invert; // closed under the condition rather than open
} GameRaceGate;

/**
 * @brief The course the level's triggers describe, gathered as they spawn and
 * validated once they all have.
 */
typedef struct {
  uint64_t checkpoints; // bit N - 1 is set once checkpoint N has spawned
  uint64_t splits;      // likewise for splits 1 through N
  uint64_t stages;      // likewise for stages 2 through N; a run begins in stage 1
  uint16_t checkpointCount, splitCount, stageCount;
  uint16_t startCount;
  uint16_t finishCount;
  struct GameEntity *barriers[RACE_MAX_BARRIERS]; // the func_race_* brushes, in spawn order
  uint16_t barrierCount;
  bool malformed, splitsMalformed, stagesMalformed; // a number out of range was seen
  bool valid;        // checkpoints 1 through N and a finish; nothing else bears on it
  bool splitsValid; // splits 1 through N, so they time
  bool stagesValid; // stages 2 through N, each with somewhere to return to
} GameRaceCourse;

/**
 * @brief One attempt at the course. Lives on `GameClient`, so a respawn clears
 * it, which is what a death means to a run.
 */
typedef struct {
  GameRaceRunState state;
  GameRaceMode mode; // the mode the run was started in, which is what decides whether it counts
  PMovement movement; // the movement it was started under, which is what a record is comparable within
  uint16_t checkpointCount;
  uint16_t splitCount;
  uint16_t stage; // the one under way, from 1
  uint32_t startTime;
  uint32_t elapsed; // set on finish
  uint32_t checkpointTimes[RACE_MAX_CHECKPOINTS]; // from the start
  uint32_t splitTimes[RACE_MAX_CHECKPOINTS];
  uint32_t stageTimes[RACE_MAX_CHECKPOINTS]; // stageTimes[N - 2] is when stage N began
  float startSpeed, endSpeed, topSpeed;
  float speedSum; // over speedSamples, for the average
  uint32_t speedSamples;
  uint8_t invalid; // GameRaceInvalid
} GameRaceRun;

/**
 * @brief A personal best on this map: one per client per movement, kept in
 * `records/<map>.rec` as brace-delimited key-value blocks, the format of
 * `maps.lst`. Keyed by the client's GUID and shown by name, so that a rename
 * keeps the record.
 */
typedef struct {
  char guid[MAX_QPATH];
  char name[MAX_QPATH];
  char ip[64];
  char date[32]; // ISO 8601, UTC
  PMovement movement;
  uint32_t params; // a hash of the PMoveParams the run was made under, for information
  uint32_t time;
  uint16_t checkpointCount, splitCount, stageCount;
  uint32_t checkpointTimes[RACE_MAX_CHECKPOINTS];
  uint32_t splitTimes[RACE_MAX_CHECKPOINTS];
  uint32_t stageTimes[RACE_MAX_CHECKPOINTS];
  float startSpeed, topSpeed, averageSpeed;
} GameRaceRecord;

/**
 * @brief The most samples a raceline holds: ten minutes at the server's tick.
 */
#define RACE_MAX_SAMPLES (600 * QUETOO_TICK_RATE)

/**
 * @brief One tick of a run: where the racer was and how they stood, in the
 * terms the ghost entity is driven in.
 */
typedef struct {
  uint32_t time; // from the start of the run
  Vec3 origin, angles;
  uint8_t animation1, animation2;
} GameRaceSample;

/**
 * @brief A run as it was raced: the samples of a run in progress on the client,
 * and of the course record on the level.
 */
typedef struct {
  GameRaceSample *samples;
  size_t count, capacity;
} GameRaceLine;

/**
 * @brief A position a practicing client asked to return to, in the spawn
 * point's terms: the origin is the floor, as `GameClientSpawn.origin` is.
 */
typedef struct {
  Vec3 origin, angles;
  bool set;
} GameRaceSpawn;

/**
 * @brief Muzzle flashes are bound to the entity that created them. This allows
 * the protocol to forego sending the origin and angles for the effect, as they
 * can be inferred from the referenced entity. Entities that the server does not
 * transmit send `MUZZLE_FLASH_WORLD` in place of an entity number, followed by
 * the origin and direction of the flash.
 */
#define MUZZLE_FLASH_WORLD -1

/**
 * @brief The muzzle flash effects the client game can render.
 */
typedef enum {
  MZ_BLASTER,
  MZ_SHOTGUN,
  MZ_SUPER_SHOTGUN,
  MZ_MACHINEGUN,
  MZ_GRENADE_LAUNCHER,
  MZ_ROCKET_LAUNCHER,
  MZ_HYPERBLASTER,
  MZ_LIGHTNING,
  MZ_RAILGUN,
  MZ_BFG10K,
  MZ_LOGOUT,

  MZ_QUAKE_SHOTGUN,
  MZ_QUAKE_SUPER_SHOTGUN,
  MZ_QUAKE_NAILGUN,
  MZ_QUAKE_SUPER_NAILGUN,
  MZ_QUAKE_GRENADE_LAUNCHER,
  MZ_QUAKE_ROCKET_LAUNCHER,

  MZ_LASER,
} GameMuzzleFlash;

/**
 * @brief Temporary entities are positional events that are not explicitly
 * bound to a game entity (`GameEntity`). Examples are explosions, certain weapon
 * trails and other short-lived effects.
 */
typedef enum {
  TE_TELEPORT,
  TE_BLASTER,
  TE_TRACER,
  TE_BULLET,
  TE_BLOOD,
  TE_SPARKS,
  TE_HYPERBLASTER,
  TE_LIGHTNING_DISCHARGE,
  TE_RAIL,
  TE_EXPLOSION,
  TE_BUBBLES,
  TE_BFG_LASER,
  TE_BFG_LASER_DEAD,
  TE_BFG,
  TE_GIB,
  TE_RIPPLE,
  TE_HOOK_IMPACT,
  TE_NAIL,
  TE_AI_NODE,
  TE_AI_NODE_LINK
} GameTempEntity;

/**
 * @brief Sound playback flags.
 */
#define SOUND_ENTITY    (1 << 0)
#define SOUND_ORIGIN    (1 << 1)
#define SOUND_PITCH     (1 << 2)
#define SOUND_GAIN      (1 << 3)
#define SOUND_RELATIVE  (1 << 4)

/**
 * @brief Sound playback dispatch. Sounds may be associated with an entity, or simply positioned.
 */
typedef struct {

  /**
   * @brief ConfigString index of the sample to play.
   */
  int32_t index;

  /**
   * @brief Sound flags; see SOUND_*.
   */
  int32_t flags;

  /**
   * @brief Entity to bind the sound to for positioning.
   */
  const struct GameEntity *entity;

  /**
   * @brief Sound origin, takes precedence over the entity origin.
   */
  const Vec3 *origin;

  /**
   * @brief Pitch shift in tones; 8 tones per octave.
   */
  int8_t pitch;

  /**
   * @brief Gain scalar in [0, 1]; 0 means use the default (1.0).
   */
  float gain;
} GamePlaySound;

/**
 * @brief Player scores are transmitted as binary to the client game module.
 */
typedef struct {

  /**
   * @brief Client number.
   */
  uint16_t client;

  /**
   * @brief Round-trip latency in milliseconds.
   */
  int16_t ping;

  /**
   * @brief Team or player color hue.
   */
  int16_t color;

  /**
   * @brief Frag or point score.
   */
  int16_t score;

    /**
   * @brief Number of deaths.
   */
  uint16_t deaths;

  /**
   * @brief Score flags.
   */
  uint8_t flags;

  /**
   * @brief Team index.
   */
  uint8_t team;

  /**
   * @brief How the client is taking part, their best on this map under the
   * level's movement in milliseconds or 0 for none, and their runs so far.
   */
  uint8_t raceMode; // GameRaceMode
  uint32_t raceBest;
  uint16_t raceRuns;
} GameScore;

/**
 * @brief Player scores flags.
 */
#define SCORE_SPECTATOR (1 << 2)
#define SCORE_AGGREGATE (1 << 3)

/**
 * @brief Game-specific entity events.
 */
typedef enum {
  EV_CLIENT_TELEPORT = EV_GAME,
  EV_CLIENT_DROWN,
  EV_CLIENT_FALL,
  EV_CLIENT_FALL_FAR,
  EV_CLIENT_FOOTSTEP,
  EV_CLIENT_GURP,
  EV_CLIENT_JUMP,
  EV_CLIENT_LAND,
  EV_CLIENT_SIZZLE,
  EV_ITEM_RESPAWN,
  EV_ITEM_PICKUP,
  EV_CLIENT_RAGDOLL,
} GameEntityEvent;

/**
 * @brief Game-specific entity state effects.
 */
#define EF_ROTATE          (EF_GAME << 0) // rotate on z
#define EF_BOB             (EF_GAME << 1) // bob on z
#define EF_INACTIVE        (EF_GAME << 2) // inactive icon for when input is not going to game
#define EF_BEAM            (EF_GAME << 3) // overloads oldOrigin for endpoint
#define EF_CORPSE          (EF_GAME << 4) // to differentiate own corpse from self
#define EF_RESPAWN         (EF_GAME << 5) // yellow shell
#define EF_QUAD            (EF_GAME << 6) // blue-green shell
#define EF_RACE_GHOST      (EF_GAME << 7) // the course record run, wearing the viewer's skin
#define EF_DESPAWN         (EF_GAME << 11) // translucent
#define EF_LIGHT           (EF_GAME << 12) // colored light
#define EF_LIGHT_PULSE     (EF_GAME << 13) // pulse EF_LIGHT radius
#define EF_TEAM_TINT       (EF_GAME << 14) // tint by the team color provided
#define EF_INVISIBILITY    (EF_GAME << 15) // ring of shadows (invisible shell)
#define EF_INVULNERABILITY (EF_GAME << 16) // invulnerability shell
#define EF_MODULATE        (EF_GAME << 17) // boost mesh brightness; mirrored in r_types.h

/**
 * @brief The lightning gun overrides animation1 to inform the client what
 * kind of trail to render.
 */
#define LIGHTNING_NO_HIT    0
#define LIGHTNING_SOLID_HIT 1

/**
 * @brief Game-specific entity state trails.
 */
typedef enum {
  TRAIL_BLASTER = TRAIL_GAME,
  TRAIL_GRENADE,
  TRAIL_ROCKET,
  TRAIL_HYPERBLASTER,
  TRAIL_LIGHTNING,
  TRAIL_BFG,
  TRAIL_TELEPORTER,
  TRAIL_GIB,
  TRAIL_FIREBALL,
  TRAIL_HOOK,
  TRAIL_PLAYER_SPAWN,
  TRAIL_QUAKE_NAIL,
  TRAIL_QUAKE_GRENADE,
  TRAIL_LASER,
} GameEntityTrail;

/**
 * @brief Scoreboard background color hues.
 */
#define TEAM_COLOR_RED    color_hue_red
#define TEAM_COLOR_BLUE   color_hue_blue
#define TEAM_COLOR_YELLOW color_hue_yellow
#define TEAM_COLOR_GREEN  color_hue_green

/**
 * @brief Team ID
 */
typedef enum {
  TEAM_NONE = -1,
  TEAM_RED,
  TEAM_BLUE,
  TEAM_YELLOW,
  TEAM_GREEN,

  MAX_TEAMS
} GameTeamId;

/**
 * @brief Entity state model number to indicate that the entity is a client.
 * When this is set, the model should be resolved from `CS_CLIENTS`.
 */
#define MODEL_CLIENT 0xff

/**
 * @brief Weapon handedness.
 */
typedef enum {
  HAND_CENTER,
  HAND_RIGHT,
  HAND_LEFT
} GameHand;

/**
 * @brief Game modes. These are selected via `g_gameplay` and sent to client via ConfigString.
 * @details `GAMEPLAY_TEAMS` is a high bit OR'd onto a base mode to indicate that
 * teams are enabled, e.g. `GAMEPLAY_TEAM_DEATHMATCH` is `GAMEPLAY_DEATHMATCH | GAMEPLAY_TEAMS`.
 * Code that needs only the base mode MUST mask it off, e.g. `gameplay & ~GAMEPLAY_TEAMS`.
 */
typedef enum {
  GAMEPLAY_DEATHMATCH = 0,
  GAMEPLAY_INSTAGIB = 1,
  GAMEPLAY_ARENA = 2,

  GAMEPLAY_TEAMS = (1 << 3),

  GAMEPLAY_TEAM_DEATHMATCH = GAMEPLAY_DEATHMATCH | GAMEPLAY_TEAMS,
  GAMEPLAY_TEAM_INSTAGIB = GAMEPLAY_INSTAGIB | GAMEPLAY_TEAMS,
  GAMEPLAY_TEAM_ARENA = GAMEPLAY_ARENA | GAMEPLAY_TEAMS
} GameplayId;

/**
 * @brief One of the six modes `GameplayId` defines, paired with the
 * canonical `g_gameplay` cvar string and menu label for it.
 */
typedef struct {
  GameplayId id;
  const char *name;
  const char *label;
} Gameplay;

/**
 * @brief The canonical table of every gameplay mode, in menu order. Defined
 * identically in every module's `g_types.h`, so `game.so` and `cgame.so` each
 * get their own compiled copy through header inclusion - no cross-binary
 * linkage, and no drift, since it is one source text.
 */
static const Gameplay gGameplayModes[] = {
  { GAMEPLAY_DEATHMATCH,      "deathmatch",      "Deathmatch" },
  { GAMEPLAY_TEAM_DEATHMATCH, "team_deathmatch", "Team Deathmatch" },
  { GAMEPLAY_INSTAGIB,        "instagib",        "Instagib" },
  { GAMEPLAY_TEAM_INSTAGIB,   "team_instagib",   "Team Instagib" },
  { GAMEPLAY_ARENA,           "arena",           "Arena" },
  { GAMEPLAY_TEAM_ARENA,      "team_arena",      "Team Arena" },
};

/**
 * @brief Item sets select which weapon and ammo roster a map uses.
 */
typedef enum {
  ITEMS_DEFAULT,
  ITEMS_QUAKE
} GameItems;

// GameItemType and GameItemTag are defined in bg_item.h

/**
 * @brief Weapon flags provide hints to indicate weapon use.
 */
typedef enum {
  WF_PROJECTILE  = (1 << 0),
  WF_HITSCAN     = (1 << 1),
  WF_TIMED       = (1 << 2),
  WF_EXPLOSIVE   = (1 << 3),
  WF_SHORT_RANGE = (1 << 4),
  WF_MED_RANGE   = (1 << 5),
  WF_LONG_RANGE  = (1 << 6)
} GameWeaponFlags;

/**
 * @brief Armor attributes.
 */
typedef struct {

  /**
   * @brief Armor type tag.
   */
  GameItemTag tag;

  /**
   * @brief Protection fraction against normal damage.
   */
  float normalProtection;

  /**
   * @brief Protection fraction against energy damage.
   */
  float energyProtection;
} GameArmorInfo;

#if defined(__G_LOCAL_H__)

/**
 * @brief This file will define the game-visible definitions of `GameClient`
 * and `GameEntity`. They are much larger than the server-visible definitions,
 * which are intentionally truncated stubs.
 */
typedef struct GameClient GameClient;
typedef struct GameEntity GameEntity;

/**
 * @brief Spawn flags for `GameEntity` are set in the level editor.
 */
#define SF_ITEM_TRIGGER        0x00000001
#define SF_ITEM_NO_TOUCH       0x00000002
#define SF_ITEM_HOVER          0x00000004
#define SF_ITEM_HAZARD_RESPAWN 0x00000008

/**
 * @brief These spawn flags are actually set by the game module on entities
 * that are programmatically instantiated.
 */
#define SF_ITEM_DROPPED      0x00010000
#define SF_ITEM_TARGETS_USED 0x00020000

/**
 * @brief Entity flags (`g_entity_locals.flags`). These again are mostly for
 * backwards compatibility with Quake II.
 */
#define FL_FLY        0x00000001
#define FL_SWIM       0x00000002  // implied immunity to drowning
#define FL_GOD_MODE   0x00000004
#define FL_TEAM_SLAVE 0x00000008  // not the first on the team

/**
 * @brief Move types govern the physics dispatch in `G_RunEntity`.
 */
typedef enum {
  MOVE_TYPE_NONE,
  MOVE_TYPE_NO_CLIP,
  MOVE_TYPE_PUSH,
  MOVE_TYPE_STOP,

  MOVE_TYPE_WALK,
  MOVE_TYPE_FLY,
  MOVE_TYPE_BOUNCE
} GameMoveType;

/**
 * @brief A synonym for readability; `MOVE_TYPE_THINK` implies that the entity's
 * Think function will update its origin and handle other interactions.
 */
#define MOVE_TYPE_THINK MOVE_TYPE_NONE

/**
 * @brief Items are touchable entities that players visit to acquire inventory.
 */
typedef struct GameItem {

  /**
   * @brief Static definition shared with cgame (classname, model, icon, etc.).
   */
  GameItemDef def;

  /**
   * @brief Called when a player touches the item; return false to prevent pickup.
   */
  bool (*Pickup)(GameClient *cl, GameEntity *it);

  /**
   * @brief Called when the item is activated from inventory.
   */
  void (*Use)(GameClient *cl, const struct GameItem *item);

  /**
   * @brief Called to drop the item; returns the dropped entity or `NULL`.
   */
  GameEntity *(*Drop)(GameClient *cl, const struct GameItem *item);

  /**
   * @brief Called every frame for a player holding this weapon.
   */
  void (*Think)(GameClient *cl);

  /**
   * @brief Precached model index; calculated at init.
   */
  uint16_t modelIndex;

  /**
   * @brief Precached pickup sound index; calculated at init.
   */
  uint16_t pickupSoundIndex;
} GameItem;

#define EOFS(x) (ptrdiff_t) &(((GameEntity *) 0)->x)

/**
 * @brief Movement states.
 */
typedef enum {
  MOVE_STATE_BOTTOM,
  MOVE_STATE_GOING_UP,
  MOVE_STATE_GOING_DOWN,
  MOVE_STATE_TOP,
} GameMoveState;

/**
 * @brief Physics parameters and think functions for entities which move.
 */
typedef struct {

  /**
   * @brief Starting origin.
   */
  Vec3 startOrigin;

  /**
   * @brief Starting angles.
   */
  Vec3 startAngles;

  /**
   * @brief Ending origin.
   */
  Vec3 endOrigin;

  /**
   * @brief Ending angles.
   */
  Vec3 endAngles;

  /**
   * @brief Sound played when movement begins.
   */
  uint16_t soundStart;

  /**
   * @brief Sound played while moving.
   */
  uint16_t soundMiddle;

  /**
   * @brief Sound played when movement ends.
   */
  uint16_t soundEnd;

  /**
   * @brief Acceleration rate.
   */
  float accel;

  /**
   * @brief Constant travel speed. For a ramped move, the speed at the end of the move.
   */
  float speed;

  /**
   * @brief The speed at the start of a ramped move, from which the entity is mixed towards
   * `speed` over the course of the move.
   */
  float startSpeed;

  /**
   * @brief Deceleration rate.
   */
  float decel;

  /**
   * @brief Total distance to travel.
   */
  float distance;

  /**
   * @brief Time to wait at each end before reversing.
   */
  float wait;

  /**
   * @brief Current movement state.
   */
  GameMoveState state;

  /**
   * @brief Current target destination.
   */
  Vec3 dest;

  /**
   * @brief Direction of travel.
   */
  Vec3 dir;

  /**
   * @brief Current movement speed.
   */
  float currentSpeed;

  /**
   * @brief Number of frames the move uses constant speed.
   */
  int32_t constFrames;

  /**
   * @brief Number of frames the move is accelerating.
   */
  int32_t accelFrames;

  /**
   * @brief Number of frames the move is decelerating.
   */
  int32_t decelFrames;

  /**
   * @brief Callback invoked when the move completes.
   */
  void (*Done)(GameEntity *);
} GameMoveInfo;

#define NUM_GIB_MODELS 4
#define NUM_GIB_SOUNDS 3

/**
 * @brief This structure holds references to frequently accessed media.
 */
typedef struct {
  struct GameMediaModels {
    uint16_t gibs[NUM_GIB_MODELS];

    uint16_t grenade;
    uint16_t quakeGrenade;
    uint16_t quakeNail;
    uint16_t rocket;
    uint16_t quakeRocket;

    uint16_t fireball;
  } models;

  struct GameMediaSounds {
    uint16_t gibHits[NUM_GIB_SOUNDS];
    uint16_t lava[3];
    uint16_t pain[4];

    uint16_t bfgHit;
    uint16_t bfgPrime;
    uint16_t death[2];
    uint16_t gasp;
    uint16_t gurp;
    uint16_t grenadeHit;
    uint16_t grenadeClang;
    uint16_t grenadeThrow;
    uint16_t grenadeTick;
    uint16_t quakeGrenadeHit;
    uint16_t quakeNailHit;
    uint16_t rocketFly;
    uint16_t lightningFly;
    uint16_t laserFly;
    uint16_t quadAttack;
    uint16_t quadExpire;

    uint16_t teleport;
    uint16_t quakeTeleport[5];

    uint16_t waterIn;
    uint16_t waterOut;

    uint16_t weaponNoAmmo;
    uint16_t weaponSwitch;

    uint16_t countdown[11];

    uint16_t roar;

    uint16_t chat;

    uint16_t invulnerabilityPickup;
    uint16_t invulnerabilityExpire;
    uint16_t invulnerabilityProtect;
    uint16_t invisibilityPickup;
    uint16_t invisibilityExpire;
  } sounds;

  struct GameMediaImages {
    uint16_t health;
  } images;
} GameMedia;

/**
 * @brief A list of spawn point entities available for player spawning.
 */
typedef struct {

  /**
   * @brief Number of spawn point entities.
   */
  uint32_t count;

  /**
   * @brief Array of spawn point entity pointers.
   */
  GameEntity **spots;
} GameSpawnPoints;

/**
 * @brief The main structure for all world management. This is cleared at each
 * level load.
 */
typedef struct {

  /**
   * @brief Current server frame number.
   */
  uint32_t frameNum;

  /**
   * @brief Level time in milliseconds.
   */
  uint32_t time;

  /**
   * @brief Descriptive map name (e.g. "Stress Fractures").
   */
  char message[MAX_STRING_CHARS];

  /**
   * @brief Short server map name (e.g. "fractures").
   */
  char name[MAX_QPATH];

  /**
   * @brief Resolved world gravity (maps.lst / worldspawn / g_gravity). Seeded at
   * spawn and on cvar change; hydrated into PMoveParams by G_MovementParams().
   */
  int16_t gravity;

  /**
   * @brief Active gameplay mode.
   */
  GameplayId gameplay;

  /**
   * @brief Active item set.
   */
  GameItems items;

  /**
   * @brief The player movement this level runs.
   */
  PMovement movement;

  /**
   * @brief True if team play is active.
   */
  bool teams;

      /**
   * @brief Number of active teams.
   */
  int32_t numTeams;

    /**
   * @brief Map-specified minimum clients override.
   */
  int32_t minClientsMap;

  /**
   * @brief Frag limit; game ends when a player reaches this.
   */
  int32_t fragLimit;

    /**
   * @brief Time limit in minutes; game ends when exceeded.
   */
  int32_t timeLimit;

  /**
   * @brief Background music track.
   */
  char music[MAX_STRING_CHARS];

  /**
   * @brief Level time when scores were last updated.
   */
  uint32_t scoresTime;

  /**
   * @brief Level time when intermission began.
   */
  uint32_t intermissionTime;

  /**
   * @brief Camera origin during intermission.
   */
  Vec3 intermissionOrigin;

  /**
   * @brief Camera angles during intermission.
   */
  Vec3 intermissionAngle;

  /**
   * @brief Entity currently being processed by `G_RunFrame`.
   */
  GameEntity *currentEntity;

  /**
   * @brief Global spawn points (used in non-team modes).
   */
  GameSpawnPoints spawnPoints;

  /**
   * @brief Accumulated frag events for this map, POSTed at intermission.
   */
  Vector *frags;

  /**
   * @brief The course the triggers describe, validated in `G_ConfigureLevel`.
   */
  GameRaceCourse raceCourse;

  /**
   * @brief Every personal best on record for this map, all movements, sorted
   * by movement and then time. Level memory, so the change of level frees it.
   */
  GameRaceRecord *raceRecords;
  size_t raceRecordCount, raceRecordCapacity;

  /**
   * @brief The course record's raceline under this level's movement, from
   * `records/<map>-<movement>.ghost`, and whose it is. Level memory.
   */
  GameRaceLine raceLine;
  char raceLineHolder[MAX_QPATH];
  char raceLineClient[MAX_STRING_CHARS]; // the holder's CS_CLIENTS string, for the ghost's skin
  uint32_t raceLineTime;

  } GameLevel;

/**
 * @brief Means of death.
 */
 typedef enum {
  MOD_UNKNOWN,
  MOD_BLASTER,
  MOD_SHOTGUN,
  MOD_SUPER_SHOTGUN,
  MOD_MACHINEGUN,
  MOD_GRENADE,
  MOD_GRENADE_SPLASH,
  MOD_ROCKET,
  MOD_ROCKET_SPLASH,
  MOD_HYPERBLASTER,
  MOD_HYPERBLASTER_CLIMB,
  MOD_LIGHTNING,
  MOD_LIGHTNING_DISCHARGE,
  MOD_RAILGUN,
  MOD_BFG_LASER,
  MOD_BFG_BLAST,
  MOD_QUAKE_SHOTGUN,
  MOD_QUAKE_SUPER_SHOTGUN,
  MOD_QUAKE_NAILGUN,
  MOD_QUAKE_SUPER_NAILGUN,
  MOD_QUAKE_GRENADE,
  MOD_QUAKE_GRENADE_SPLASH,
  MOD_QUAKE_ROCKET,
  MOD_QUAKE_ROCKET_SPLASH,
  MOD_QUAKE_THUNDERBOLT,
  MOD_QUAKE_THUNDERBOLT_DISCHARGE,
  MOD_WATER,
  MOD_SLIME,
  MOD_LAVA,
  MOD_CRUSH,
  MOD_HOOK,
  MOD_TELEFRAG,
  MOD_FALLING,
  MOD_SUICIDE,
  MOD_EXPLOSIVE,
  MOD_TRIGGER_HURT,
  MOD_HANDGRENADE,
  MOD_HANDGRENADE_SPLASH,
  MOD_HANDGRENADE_SUICIDE,
  MOD_HANDGRENADE_KAMIKAZE,
  MOD_FIREBALL,
  MOD_ACT_OF_GOD,
  MOD_BOB,
  MOD_BALLISTICS_BLASTER,
  MOD_BALLISTICS_SHOTGUN,
  MOD_BALLISTICS_SUPER_SHOTGUN,
  MOD_BALLISTICS_MACHINEGUN,
  MOD_BALLISTICS_GRENADE,
  MOD_BALLISTICS_ROCKET,
  MOD_BALLISTICS_HYPERBLASTER,
  MOD_BALLISTICS_LIGHTNING,
  MOD_BALLISTICS_RAILGUN,
  MOD_BALLISTICS_BFG,
  MOD_BALLISTICS_QUAKE_SHOTGUN,
  MOD_BALLISTICS_QUAKE_SUPER_SHOTGUN,
  MOD_BALLISTICS_QUAKE_NAILGUN,
  MOD_BALLISTICS_QUAKE_SUPER_NAILGUN,
  MOD_BALLISTICS_QUAKE_GRENADE,
  MOD_BALLISTICS_QUAKE_ROCKET,
  MOD_BALLISTICS_QUAKE_THUNDERBOLT,
  MOD_BALLISTICS_LASER,
  MOD_BALLISTICS_GIBLETS,
  MOD_TURRET_BLASTER,
  MOD_TURRET_SHOTGUN,
  MOD_TURRET_SUPER_SHOTGUN,
  MOD_TURRET_MACHINEGUN,
  MOD_TURRET_GRENADE,
  MOD_TURRET_ROCKET,
  MOD_TURRET_HYPERBLASTER,
  MOD_TURRET_LIGHTNING,
  MOD_TURRET_RAILGUN,
  MOD_TURRET_BFG,
  MOD_TURRET_QUAKE_SHOTGUN,
  MOD_TURRET_QUAKE_SUPER_SHOTGUN,
  MOD_TURRET_QUAKE_NAILGUN,
  MOD_TURRET_QUAKE_SUPER_NAILGUN,
  MOD_TURRET_QUAKE_GRENADE,
  MOD_TURRET_QUAKE_ROCKET,
  MOD_TURRET_QUAKE_THUNDERBOLT,
  MOD_TURRET_LASER,
  MOD_TURRET_GIBLETS,
  MOD_FRIENDLY_FIRE = 0x8000000
} g_means_of_death;

/**
 * @brief Damage flags. These can be and often are combined.
 */
#define DMG_RADIUS   0x1  // damage was indirect
#define DMG_ENERGY   0x2  // damage is from an energy based weapon
#define DMG_BULLET   0x4  // damage is from a bullet
#define DMG_NO_ARMOR 0x8  // armor does not protect from this damage
#define DMG_NO_GOD   0x10  // armor and god mode have no effect

/**
 * @brief Damage parameters for `G_Damage`.
 */
typedef struct {

 /**
  * @brief Entity receiving the damage.
  */
	GameEntity *target;

 /**
  * @brief Entity that dealt the damage (projectile, explosion, etc.).
  */
	GameEntity *inflictor;

 /**
  * @brief Entity responsible for the damage (player, etc.).
  */
	GameEntity *attacker;

 /**
  * @brief Direction the damage came from.
  */
	Vec3 dir;

 /**
  * @brief World point where the damage was applied.
  */
	Vec3 point;

 /**
  * @brief Surface normal at the damage point.
  */
	Vec3 normal;

 /**
  * @brief Amount of damage to apply.
  */
	int32_t damage;

 /**
  * @brief Knockback force to apply.
  */
	int32_t knockback;

 /**
  * @brief Damage flags (`DMG_RADIUS`, `DMG_ENERGY`, etc.).
  */
	int32_t flags;

 /**
  * @brief Means of death identifier.
  */
	g_means_of_death mod;
} GameDamage;

/**
 * @brief Parameters for a burst of giblets, as scattered by a dying corpse or a
 * `ballistics_giblets`.
 */
typedef struct {

  /**
   * @brief The origin the giblets are scattered from.
   */
  Vec3 origin;

  /**
   * @brief The velocity the giblets inherit, before randomization.
   */
  Vec3 velocity;

  /**
   * @brief The number of giblets to scatter.
   */
  int32_t count;

  /**
   * @brief Upward velocity added to each giblet.
   */
  float lift;

  /**
   * @brief True to include a head among the giblets.
   */
  bool head;

  /**
   * @brief Damage each giblet inflicts on contact, or zero for harmless giblets.
   */
  int32_t damage;

  /**
   * @brief Knockback each giblet applies on contact.
   */
  int32_t knockback;

  /**
   * @brief The entity credited with damage the giblets inflict.
   */
  GameEntity *attacker;

  /**
   * @brief The means of death the giblets inflict.
   */
  uint32_t mod;

  /**
   * @brief Milliseconds each giblet is visible for, after which it sinks and fades as a
   * corpse's giblets do; zero to linger the full lifetime of a corpse's instead.
   */
  uint32_t lifetime;

} GameGiblets;

/**
 * @brief The name for the CTF skin used in team games.
 */
#define DEFAULT_TEAM_SKIN "ctf"

/**
 * @brief There are four teams in the default game module.
 */
typedef struct {

  /**
   * @brief Team identifier, used for comparison instead of pointer equality.
   */
  GameTeamId id;

  /**
   * @brief Short team name for HUD display.
   */
  char name[16];

  /**
   * @brief Team skin name.
   */
  char skin[MAX_QPATH];

    /**
   * @brief Spawn point classname.
   */
  char spawn[MAX_QPATH];

  /**
   * @brief Team player colors.
   */
  Color shirt, pants, helmet;

  /**
   * @brief Team color hue.
   */
  int16_t color;

    /**
   * @brief Team score.
   */
  int16_t score;

    /**
   * @brief Spawn points for this team.
   */
  GameSpawnPoints spawnPoints;

  } GameTeam;

/**
 * @brief The default player model
 */
#define DEFAULT_USER_MODEL "enforcer"

/**
 * @brief The default player skin
 */
#define DEFAULT_USER_SKIN "default"

/**
 * @brief The default user info string (name and skin).
 */
#define DEFAULT_USER_INFO "\\name\\newbie\\skin\\" DEFAULT_USER_MODEL "/" DEFAULT_USER_SKIN

/**
 * @brief The full length of a net name, in bytes (including non-printables).
 */
#define MAX_NET_NAME 64

/**
 * @brief The maximum printable length of a net name.
 */
#define MAX_NET_NAME_PRINTABLE 15

/**
 * @brief This structure contains client data that persists over multiple spawns.
 */
typedef struct {

  /**
   * @brief Frame number when the client first entered the game.
   */
  uint32_t firstFrame;

  /**
   * @brief Raw user info key-value string.
   */
  char userInfo[MAX_INFO_STRING_STRING];

  /**
   * @brief Display name.
   */
  char netName[MAX_NET_NAME];

  /**
   * @brief Player model/skin path.
   */
  char skin[MAX_QPATH];

  /**
   * @brief Weapon handedness preference.
   */
  GameHand hand;

  /**
   * @brief The standing box last published on `CS_CLIENTS`, so that a change of
   * movement parameters republishes it.
   */
  Box3 standingBounds;

  /**
   * @brief Non-zero if weapons should auto-switch on pickup.
   */
  uint16_t autoSwitch;

  /**
   * @brief The player's selected hook style.
   */
  GameHookStyle hookStyle;

    /**
   * @brief Current team assignment.
   */
  GameTeam *team;

  /**
   * @brief Player effect color hue.
   */
  int16_t color;

  /**
   * @brief Player clothing colors.
   */
  Color shirt, pants, helmet;

  /**
   * @brief Current score.
   */
  int16_t score;

    /**
   * @brief Number of deaths.
   */
  uint16_t deaths;

  /**
   * @brief True if the player has admin privileges.
   */
  bool admin;

  /**
   * @brief True if the player is a spectator.
   */
  bool spectator;

  /**
   * @brief True if the player is muted.
   */
  bool muted;

  /**
   * @brief Mask of clients this one has muted, in both chat and voice.
   */
  uint64_t mutedClients;

  /**
   * @brief Per-install GUID sent via userinfo, used for stats reporting.
   */
  char guid[MAX_QPATH];

  /**
   * @brief Racing or practicing, chosen by the client and kept across respawns.
   */
  GameRaceMode raceMode;

  /**
   * @brief Where `kill` returns a practicing client to, once they have `store`d.
   */
  GameRaceSpawn raceSpawn;

  /**
   * @brief Whether the course record's ghost runs alongside this client's runs.
   */
  bool raceGhost;

  /**
   * @brief The runs started on this map, for the HUD.
   */
  uint16_t raceRuns;
} GameClientPersistent;

/**
 * @brief This structure is cleared on each spawn, with the persistent structure
 * explicitly copied over to preserve team membership, etc. This structure
 * extends the server-visible definition to provide all of the state management
 * the game module requires.
 */
struct GameClient {

  /**
   * @brief What the server reads out of a client. This MUST be the first member:
   * the server reads these fields at offset zero, and C guarantees a pointer to
   * a structure points at its first member. Its fields are reached without
   * naming it, so `cl->entity` is the entity bound to this client.
   */
  ServerGameClient;

  /**
   * @brief Grappling hook state, reset on respawn.
   */
  GameClientHook hook;

  /**
   * @brief Data that persists across respawns.
   */
  GameClientPersistent persistent;

  /**
   * @brief Most recently received movement command.
   */
  PMoveCmd cmd;

  /**
   * @brief The run in progress, cleared with the rest of this structure on respawn.
   */
  GameRaceRun raceRun;

  /**
   * @brief Bit N is set while `race_course.barriers[N]` lets this client pass,
   * as decided at the end of the last frame and sent to them then.
   */
  uint32_t racePassable;

  /**
   * @brief The race trigger last touched and when, so that standing in one does
   * not fire it every frame.
   */
  const GameEntity *raceTrigger;
  uint32_t raceTriggerTime;

  /**
   * @brief A start zone entered but not yet left or jumped out of, for the
   * start modes that begin the run on the way out rather than on the way in.
   */
  const GameEntity *raceStart;

  /**
   * @brief The course record's ghost running alongside this client, or NULL.
   */
  GameEntity *raceGhost;

  /**
   * @brief Item inventory counts indexed by item index.
   */
  int16_t inventory[ITEM_TOTAL];

  /**
   * @brief Currently active weapon.
   */
  const GameItem *weapon;

  /**
   * @brief Previously active weapon.
   */
  const GameItem *prevWeapon;

  /**
   * @brief Weapon currently being switched to.
   */
  const GameItem *nextWeapon;

  /**
   * @brief Inventory index of the current weapon's ammo.
   */
  uint16_t ammoIndex;

  /**
   * @brief Current frame button state.
   */
  uint32_t buttons;

  /**
   * @brief Previous frame button state.
   */
  uint32_t oldButtons;

  /**
   * @brief Buttons pressed this frame (edge-triggered).
   */
  uint32_t latchedButtons;

  /**
   * @brief Level time when the weapon think was last called.
   */
  uint32_t weaponThinkTime;

  /**
   * @brief Weapon may fire again when time exceeds this.
   */
  uint32_t weaponFireTime;

  /**
   * @brief Level time when the weapon was last fired.
   */
  uint32_t weaponFiredTime;

  /**
   * @brief Level time when the weapon was last changed.
   */
  uint32_t weaponChangeTime;

  /**
   * @brief Water level from the previous frame.
   */
  PMoveWaterLevel oldWaterLevel;

          /**
   * @brief Alternating barrel index for the Quake nailgun.
   * Odd = right barrel (+2 units), even = left barrel (-2 units).
   */
  uint32_t quakeNailgunBarrel;

  /**
   */
  int16_t damageArmor;

  /**
   * @brief Damage taken to health this frame.
   */
  int16_t damageHealth;

  /**
   * @brief Damage inflicted on other clients this frame.
   */
  int16_t damageInflicted;

  /**
   * @brief Maximum armor the client can carry.
   */
  int16_t maxArmor;

  /**
   * @brief Maximum health the client can be boosted to.
   */
  int16_t maxBoostHealth;

  /**
   * @brief Horizontal speed after the last move.
   */
  float speed;

  /**
   * @brief Current aiming direction angles.
   */
  Vec3 angles;

  /**
   * @brief Aiming direction vectors.
   */
  Vec3 forward, right, up;

  /**
   * @brief Angles received in the last movement command.
   */
  Vec3 cmdAngles;

  /**
   * @brief View kick angles accumulated this frame.
   */
  Vec3 kickAngles;

  /**
   * @brief Client may respawn when time exceeds this.
   */
  uint32_t respawnTime;

  /**
   * @brief The time at which this client died, used to gate the forced
   * BOTH_DEATHx -> BOTH_DEADx animation transition (see DEATH_ANIM_SETTLE_TIME).
   */
  uint32_t deathTime;

  /**
   * @brief Respawn protection expires at this time.
   */
  uint32_t respawnProtectionTime;

  /**
   * @brief Level time when the client last touched the ground.
   */
  uint32_t groundTime;

  /**
   * @brief Falling damage becomes eligible when time exceeds this.
   */
  uint32_t boostTime;

  /**
   * @brief Drowning damage becomes eligible when time exceeds this.
   */
  uint32_t drownTime;

  /**
   * @brief Sizzle damage becomes eligible when time exceeds this.
   */
  uint32_t sizzleTime;

  /**
   * @brief Landing event fires when time exceeds this.
   */
  uint32_t landTime;

  /**
   * @brief Client may jump when time exceeds this.
   */
  uint32_t jumpTime;

  /**
   * @brief Pain sound may play when time exceeds this.
   */
  uint32_t painTime;

  /**
   * @brief Footstep sound plays when time exceeds this.
   */
  uint32_t footstepTime;

  /**
   * @brief Primary animation may update when time exceeds this.
   */
  uint32_t animation1Time;

  /**
   * @brief Secondary animation may update when time exceeds this.
   */
  uint32_t animation2Time;

  /**
   * @brief Held grenade detonates when time exceeds this.
   */
  uint32_t grenadeTime;

  /**
   * @brief Level time when the client began holding a primed grenade.
   */
  uint32_t grenadeHoldTime;

  /**
   * @brief Frame number when the grenade pin was pulled.
   */
  uint32_t grenadeHoldFrame;

  /**
   * @brief The grenade entity the client is currently holding.
   */
  GameEntity *heldGrenade;

  /**
   * @brief Pickup message is displayed until time exceeds this.
   */
  uint32_t pickupMsgTime;

  /**
   * @brief Last usable item picked up.
   */
  const GameItem *lastPickup;

  /**
   * @brief Client may chat when time exceeds this.
   */
  uint32_t chatTime;

  /**
   * @brief Quad damage is active while time is less than this.
   */
  uint32_t quadDamageTime;

  /**
   * @brief Quad damage countdown warning threshold.
   */
  uint32_t quadCountdownTime;

  /**
   * @brief Quad attack sound plays when time exceeds this.
   */
  uint32_t quadAttackTime;

  /**
   * @brief Invisibility is active while time is less than this.
   */
  uint32_t invisibilityTime;

  /**
   * @brief Invulnerability is active while time is less than this.
   */
  uint32_t invulnerabilityTime;

  /**
   * @brief Pentagram countdown warning threshold.
   */
  uint32_t invulnerabilityCountdownTime;

  /**
   * @brief Client being chased in spectator mode.
   */
  GameClient *chaseTarget;

  /**
   * @brief Previously chased client.
   */
  GameClient *oldChaseTarget;

  /**
   * @brief Last dropped item, used for variable expansion.
   */
  const GameItem *lastDropped;

  /**
   * @brief Death camera position and velocity, in world space. Valid while
   * `PMF_DEATH_CAM` is set on the player state.
   */
  Vec3 deathCamOrigin, deathCamVelocity;

  /**
   * @brief The displacement the camera eases through as it settles, away from
   * the point of death.
   */
  Vec3 deathCamOffset;

  /**
   * @brief The angles the death camera is looking through.
   */
  Vec3 deathCamAngles;

  /**
   * @brief The level time at which the death camera was armed.
   */
  uint32_t deathCamTime;

  /**
   * @brief True if the scoreboard layout flag should be set.
   */
  bool showScores;

  /**
   * @brief Scores may be sent when time exceeds this.
   */
  uint32_t scoresTime;

  };

typedef struct GameClient GameClient;

/**
 * @brief The `GameEntity` structure extends the server stub to
 * provide all of the state management the game module requires.
 */
struct GameEntity {

  /**
   * @brief What the server reads out of an entity. This MUST be the first member:
   * the server reads these fields at offset zero, and C guarantees a pointer to
   * a structure points at its first member. Its fields are reached without
   * naming it, so `ent->s.origin` is this entity's state origin.
   */
  ServerGameEntity;

  /**
   * @brief Spawn flags (`SF_ITEM_HOVER`, etc.).
   */
  uint32_t spawnFlags;

  /**
   * @brief Means of death this entity inflicts, for projectiles and other inflictors.
   */
  uint32_t mod;

  /**
   * @brief Entity flags (`FL_GOD_MODE`, etc.).
   */
  uint32_t flags;

  /**
   * @brief Physics move type.
   */
  GameMoveType moveType;

  /**
   * @brief Physics move parameters and state.
   */
  GameMoveInfo moveInfo;

  /**
   * @brief Clip mask (e.g. `CONTENTS_MASK_CLIP_PROJECTILE`).
   */
  int32_t clipMask;

  /**
   * @brief General-purpose timestamp.
   */
  uint32_t timestamp;

  /**
   * @brief Time of the last muzzle flash, throttling the flash rate of rapid
   * firing entities independently of how often they actually fire.
   */
  uint32_t flashTime;

  /**
   * @brief Target name to fire when triggered.
   */
  const char *target;

  /**
   * @brief This entity's target name.
   */
  const char *targetName;

  /**
   * @brief Message to print when triggered.
   */
  const char *message;

  /**
   * @brief Team name for multi-entity grouping.
   */
  const char *team;

  /**
   * @brief Cached pointer to the target entity.
   */
  GameEntity *targetEnt;

  /**
   * @brief Movement speed and acceleration parameters.
   */
  float speed, accel, decel;

  /**
   * @brief Direction of movement derived from angles.
   */
  Vec3 moveDir;

  /**
   * @brief Start and end positions for movers.
   */
  Vec3 pos1, pos2;

  /**
   * @brief Linear velocity.
   */
  Vec3 velocity;

  /**
   * @brief Angular velocity.
   */
  Vec3 avelocity;

  /**
   * @brief Entity mass used for physics calculations.
   */
  float mass;

  /**
   * @brief Level time of the next Think invocation.
   */
  uint32_t nextThink;

  /**
   * @brief Per-frame think callback.
   */
  void (*Think)(GameEntity *ent);

  /**
   * @brief Called when a mover is blocked.
   */
  void (*Blocked)(GameEntity *ent, GameEntity *other);

  /**
   * @brief Called on entity contact.
   */
  void (*Touch)(GameEntity *ent, GameEntity *other, const CmTrace *trace);

  /**
   * @brief Called when triggered.
   */
  void (*Use)(GameEntity *ent, GameEntity *other, GameEntity *activator);

  /**
   * @brief Called when damaged.
   */
  void (*Pain)(GameEntity *ent, GameEntity *other, int16_t damage, int16_t knockback);

  /**
   * @brief Called when health drops to zero.
   */
  void (*Die)(GameEntity *ent, GameEntity *attacker, uint32_t mod);

  /**
   * @brief Cooldown timer for Touch events.
   */
  uint32_t touchTime;

  /**
   * @brief Sound to play when this projectile hits a structural surface.
   */
  uint16_t hitSound;

  /**
   * @brief Time of the last push interaction.
   */
  uint32_t pushTime;

  /**
   * @brief Time of the last water ripple.
   */
  uint32_t rippleTime;

  /**
   * @brief Radius of the last water ripple.
   */
  float rippleSize;

  /**
   * @brief Current health.
   */
  int16_t health;

  /**
   * @brief Maximum health.
   */
  int16_t maxHealth;

  /**
   * @brief True if the entity is dead.
   */
  bool dead;

  /**
   * @brief True if the entity can receive damage.
   */
  bool takeDamage;

  /**
   * @brief Damage dealt on contact.
   */
  int16_t damage;

  /**
   * @brief Knockback applied on contact.
   */
  int16_t knockback;

  /**
   * @brief Radius for splash damage.
   */
  float damageRadius;

  /**
   * @brief General-purpose counter (usage varies by entity type).
   */
  int32_t count;

  /**
   * @brief Current enemy entity.
   */
  GameEntity *enemy;

  /**
   * @brief Entity that last activated/triggered this entity.
   */
  GameEntity *activator;

  /**
   * @brief First entity in a team chain.
   */
  GameEntity *teamMaster;

  /**
   * @brief Next entity in the team chain.
   */
  GameEntity *teamNext;

  /**
   * @brief Looping ambient sound index.
   */
  uint16_t sound;

  /**
   * @brief Time to wait between activations.
   */
  float wait;

  /**
   * @brief Delay before firing targets after activation.
   */
  float delay;

  /**
   * @brief Random time added to the delay.
   */
  float random;

  /**
   * @brief Ground trace result from the last physics frame.
   */
  CmTrace ground;

  /**
   * @brief Content type of water the entity is submerged in.
   */
  int32_t waterType;

  /**
   * @brief Current water immersion level.
   */
  PMoveWaterLevel waterLevel;

  /**
   * @brief Item definition for bonus item entities.
   */
  const GameItem *item;

  /**
   * @brief Projectile definition for `ballistics_*` and `turret_*` entities, resolved from their
   * classname at spawn time. Incomplete here; the definition is private to g_entity_target.c.
   */
  const struct GameBallisticsType *ballistics;

  /**
   * @brief AI navigation node for item path tracking.
   */
  AiNodeId node;

  /**
   * @brief True if the entity should advance along the item path.
   */
  bool moveNode;

  /**
   * @brief What this brush is to a racer's movement, for the `func_race_*` classes.
   */
  GameRaceBarrier raceBarrier;
  GameRaceGate raceGate;
  uint16_t raceBarrierSlot; // its index in race_course.barriers
};

typedef struct GameEntity GameEntity;

#endif
