set -e

ENV=`echo $JOB_NAME|cut -d\-  -f3-10`

DEPS="SDL-devel SDL_image-devel SDL_mixer-devel curl-devel physfs-devel glib2-devel libjpeg-turbo-devel libtool zlib-devel ncurses-devel check check-devel"

/usr/bin/mock -r ${ENV} --clean
/usr/bin/mock -r ${ENV} --init
/usr/bin/mock -r ${ENV} --install ${DEPS}
/usr/bin/mock -r ${ENV} --copyin . "/tmp/quake2world"

/usr/bin/mock -r ${ENV} --shell "

mkdir -p ~/.quake2world/default/maps
touch ~/.quake2world/default/maps/torn.bsp
echo -e '// generated by Quake2World, do not modify\n' > ~/.quake2world/default/quake2world.cfg

cd /tmp/quake2world
libtoolize --force
autoreconf -i --force
./configure --prefix=/tmp/quake2world-'${ENV}' --with-tests --with-master
make
make check
make install
" 
rm -Rf ${WORKSPACE}/jenkins-quake2world*
/usr/bin/mock -r ${ENV} --copyout "/tmp/quake2world-${ENV}" "${WORKSPACE}/${BUILD_TAG}"
/usr/bin/mock -r ${ENV} --clean
cd ${WORKSPACE}
tar czf ${BUILD_TAG}.tgz ${BUILD_TAG}

