#!/bin/bash -e
#
# Create unit test fixtures for continuous integration builds
#

mkdir -p ~/.quake2world/default/maps
touch ~/.quake2world/default/maps/torn.bsp

echo -e '// generated by Quake2World, do not modify\n' > ~/.quake2world/default/quake2world.cfg
