#!/bin/bash
set -e
set -x

source ~/.profile 
mkdir -p ~/.quake2world/default/maps
touch ~/.quake2world/default/maps/torn.bsp
echo "// generated by Quake2World, do not modify\n" > ~/.quake2world/default/quake2world.cfg

pwd

autoreconf -i --force
./configure --prefix=/Users/q2wbuild/jenkins/quake2world-result --with-tests --with-master
make distclean
./configure --prefix=/Users/q2wbuild/jenkins/quake2world-result --with-tests --with-master
make
#make check
make install

