#version 460
#extension GL_EXT_ray_tracing : require

layout(binding = 0, set = 0) uniform accelerationStructureEXT tlas;
layout(binding = 1, set = 0, rgba8) uniform image2D out_image;
layout(push_constant) uniform PC { vec4 eye; vec4 target; vec4 light; } pc;

layout(location = 0) rayPayloadEXT vec3 hit_value;

void main() {
  const vec2 uv = (vec2(gl_LaunchIDEXT.xy) + 0.5) / vec2(gl_LaunchSizeEXT.xy);
  const vec2 d = uv * 2.0 - 1.0;

  // Quetoo / Quake use a Z-up coordinate system
  const vec3 world_up = vec3(0.0, 0.0, 1.0);
  vec3 eye = pc.eye.xyz;
  vec3 fwd = normalize(pc.target.xyz - eye);
  vec3 right = normalize(cross(fwd, world_up));
  vec3 up = cross(right, fwd);

  const float tan_half = 0.62;
  const float aspect = float(gl_LaunchSizeEXT.x) / float(gl_LaunchSizeEXT.y);
  vec3 dir = normalize(fwd + d.x * tan_half * aspect * right - d.y * tan_half * up);

  hit_value = vec3(0.0);
  traceRayEXT(tlas, gl_RayFlagsOpaqueEXT, 0xFF, 0, 0, 0, eye, 0.5, dir, 1.0e6, 0);
  imageStore(out_image, ivec2(gl_LaunchIDEXT.xy), vec4(hit_value, 1.0));
}
